//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GGTong.rc
//
#define IDCACEL                         2
#define IDB_RESTORE                     3
#define IDB_SAVEAS_DEFAULT              3
#define ID_BUTTON_SELALL                3
#define IDC_BUTTON_STOPTIMECLOSE        3
#define ID_ALLSETTING                   3
#define IDCANCEL2                       4
#define IDC_BUTTON_ARBITRADE_DEL        4
#define IDD_ABOUTBOX                    100
#define IDD_DEMOBARVIEW                 101
#define IDR_HTML_DLGTRADEDOWNLOAD       103
#define IDR_MAINFRAME                   128
#define IDR_GGTONGTYPE                  129
#define IDD_EDIT_ZHOUQI                 131
#define IDR_TABS                        133
#define IDB_GUI_DOCKBAR                 138
#define IDB_TAB                         139
#define IDB_MENU256_MAINFRAME           143
#define IDD_LAYOUTADJUST                145
#define IDD_KEYBOARD                    146
#define IDB_GRID_REPORT                 147
#define IDB_GRID_REPORT1                148
#define IDR_MENU_KLINE                  149
#define IDR_MENU_KLINEARB               150
#define IDR_MENU_TRENDARB               151
#define IDR_MENU_SINGLE_REPORT          152
#define IDD_DIALOG_SYSTEM_SET           153
#define IDD_DIALOG_SYSFACE              154
#define IDD_DIALOG_SYSPARAMETER         155
#define IDD_DIALOG_SELFDRAW             156
#define IDD_DIALOG_GRIDHEAD             157
#define IDD_DIALOG_MERCH                158
#define IDD_DIALOG_TEST                 159
#define IDR_MENU_STATUSBAR              159
#define IDD_DIALOG_SPIRITE              160
#define IDD_DIALOG_LOGIN                161
#define IDD_DIALOG_LOGIN2               162
#define IDD_DIALOG_CONNECTSET           163
#define IDD_DIALOG_HOSTSET              164
#define IDD_DIALOG_BLOCK                165
#define IDB_TREEIMAGE                   170
#define IDD_DIALOG_BLOCK_SET            171
#define IDD_DIALOG_MERCH_SEL            172
#define IDD_DIALOG_BLOCK_MAG            173
#define IDD_DIALOG_WORKSPACE            174
#define IDD_DIALOG_WSPNAME              175
#define IDR_MENU_BLOCK                  177
#define IDD_DIALOG_BLOCK_SEL            178
#define IDD_DIALOG_FORMULA              180
#define IDD_EDIT_HS                     183
#define IDD_DIALOG_TIME_WAIT            184
#define IDB_HORIZONTAL_SCROLLBAR_LEFTARROW 201
#define IDB_HORIZONTAL_SCROLLBAR_RIGHTARROW 202
#define IDB_HORIZONTAL_SCROLLBAR_CHANNEL 203
#define IDB_HORIZONTAL_SCROLLBAR_THUMB  204
#define IDB_HORIZONTAL_SCROLLBAR_THUMB_NO_COLOR 205
#define IDB_VERTICAL_SCROLLBAR_UPARROW  206
#define IDB_VERTICAL_SCROLLBAR_DOWNARROW 207
#define IDB_VERTICAL_SCROLLBAR_CHANNEL  208
#define IDB_VERTICAL_SCROLLBAR_THUMB    209
#define IDB_VERTICAL_SCROLLBAR_THUMB_NO_COLOR 210
#define IDB_HORIZONTAL_SCROLLBAR_LEFTARROW_BACAI 220
#define IDB_HORIZONTAL_SCROLLBAR_RIGHTARROW_BACAI 221
#define IDB_HORIZONTAL_SCROLLBAR_CHANNEL_BACAI 222
#define IDB_HORIZONTAL_SCROLLBAR_THUMB_BACAI 223
#define IDB_HORIZONTAL_SCROLLBAR_THUMB_NO_COLOR_BACAI 224
#define IDD_EDIT_TJXG_K                 260
#define IDD_DIALOG_UPDATE               261
#define IDI_ICON_KMERCH                 263
#define IDI_ICON_KSHOTCUT               265
#define IDI_ICON_KKLINE                 266
#define IDI_ICON_KBLOCK                 267
#define IDI_ICON_WSP                    268
#define IDI_ICON_CFM                    269
#define IDI_ICON_VMG                    270
#define IDR_MAINFRAME_SMALL             271
#define IDB_FORIOVIEWREPORT             272
#define IDB_CAPTION                     273
#define IDB_CFMBTNS                     274
#define IDB_MFMBTNS                     275
#define IDB_CAPTION2                    278
#define IDB_MAINCAPTION                 279
#define IDB_MAINCAPTION2                280
#define IDB_NAME                        281
#define IDD_DIALOG_FORMULA2             282
#define IDD_DIALOG_INDEX_PARAM          283
#define IDD_DIALOG_TABNAME              284
#define IDR_MENU_CHG                    285
#define IDB_FORMULA                     287
#define IDR_SELFDRAW                    288
#define IDC_CUR_DRAG_UPDOWN             290
#define IDC_CUR_DRAG_LEFT               291
#define IDC_CUR_DRAG_RIGHT              292
#define IDC_CUR_DRAG_LEFT_STOP          293
#define IDD_DIALOG_NETWORK              293
#define IDC_CUR_DRAG_RIGHT_STOP         294
#define IDC_CUR_DRAG_UPDOWN_STOP        295
#define IDD_DIALOG_SETTEXT              297
#define IDB_NET_ON2                     300
#define IDB_NET_OFF                     301
#define IDB_NET_ON1                     302
#define IDB_NET_ONOFF                   303
#define IDC_CUR_SDMOVE                  304
#define IDC_CUR_SDCHG                   305
#define IDC_CUR_SDNONE                  306
#define IDD_DIALOG_BROKERWATCH          307
#define IDB_SMALL_TITTLE                308
#define IDB_BIG_TITTLE                  309
#define IDB_DLGBUTTONS                  310
#define IDD_DIALOG_WAIT                 311
#define IDD_DIALOG_SD_SETTING           313
#define IDB_BORDER                      315
#define IDD_TRACE                       316
#define IDD_DIALOG_RECENTMERCH          319
#define IDD_DIALOG_ALARM                320
#define IDD_DIALOG_ALARMSET             321
#define IDB_ALARM_ON                    324
#define IDB_ALARM_OFF                   325
#define IDB_LAYOUTSET_ACTIVE            326
#define IDB_LAYOUTSET_INACTIVE          327
#define IDB_CAPTION_HISTORY             330
#define IDD_DIALOG_SELECT_STOCK         331
#define IDD_DIALOG_BLOCK_CHOOSE_STOCK   333
#define IDD_DIALOG_PROGRESS_CHOOSE_STOCK 334
#define IDB_F7_ACTIVE                   336
#define IDB_F7_INACTIVE                 337
#define IDD_DIALOG_TRENDINDEX           338
#define IDB_TRENDINDEX                  339
#define IDB_TREND_TITLE                 340
#define IDR_PNG_DLG_BTN                 343
#define IDR_PNG_MAINFRAME_BTN           344
#define IDR_PNG_CHILDFRAME_BTN          345
#define IDR_PNG_CHILDFRAME_BTN_LAYOUT   346
#define IDR_PNG_CHILDFRAME_BTN_F7       347
#define IDR_PNG_CHILDFRAME_CAPTION_ACTIVE 348
#define IDR_PNG_CHILDFRAME_CAPTION_INACTIVE 349
#define IDR_PNG_MAINFRAME_CAPTION       352
#define IDR_PNG_MAINFRAME_TITLE_ACTIVE  353
#define IDR_PNG_MAINFRAME_TITLE_INACTIVE 354
#define IDR_PNG_ALARM_ON                355
#define IDR_PNG_ALARM_OFF               356
#define IDR_PNG_NET_ON1                 357
#define IDR_PNG_NET_OFF                 358
#define IDR_PNG_IOVIEWTITLE_SELF        359
#define IDR_PNG_TREND_INDEX_WUSD        362
#define IDR_PNG_TREND_INDEX_WUSU        363
#define IDR_PNG_TREND_INDEX_WSU         364
#define IDR_PNG_TREND_INDEX_WSD         365
#define IDR_PNG_TREND_INDEX_SUSU        366
#define IDR_PNG_TREND_INDEX_SUSD        367
#define IDR_PNG_TREND_INDEX_SSU         368
#define IDR_PNG_TREND_INDEX_SSD         369
#define IDR_PNG_TREND_INDEX_SHAKE       370
#define IDR_PNG_TREND_INDEX_NUSD        371
#define IDR_PNG_TREND_INDEX_NUSU        372
#define IDR_PNG_TREND_INDEX_NSU         373
#define IDR_PNG_TREND_INDEX_NSD         374
#define IDR_PNG_TREND_INDEX_KTRC        375
#define IDR_PNG_TREND_INDEX_KTOC        376
#define IDR_PNG_TREND_INDEX_KTCC        377
#define IDR_PNG_TREND_INDEX_KTAC        378
#define IDR_PNG_TREND_INDEX_DTRC        379
#define IDR_PNG_TREND_INDEX_DTOC        380
#define IDR_PNG_TREND_INDEX_DTCC        381
#define IDR_PNG_TREND_INDEX_DTAC        382
#define IDB_GUITAB_NORMAL               387
#define IDB_GUITAB_SELECTED             388
#define IDR_PNG_WSP                     389
#define IDR_PNG_CFM                     390
#define IDR_PNG_VMG                     391
#define IDR_PNG_MERCH                   392
#define IDR_PNG_BLOCK                   393
#define IDR_PNG_SHORT_CUT               394
#define IDR_PNG_INDEX                   395
#define IDR_PNG_DIALOG_CAPTION_BIG      396
#define IDR_PNG_DIALOG_CAPTION_SMALL    397
#define IDB_DLG_CAPTION_BIG             399
#define IDB_DLG_CAPTION_SMALL           400
#define IDR_PNG_STATUSBAR               401
#define IDR_PNG_NET_ON2                 402
#define IDR_PNG_IOVIEWTITLE_F7_NORMAL   403
#define IDR_PNG_IOVIEWTITLE_F7_FOCUS    404
#define IDR_PNG_IOVIEWTITLE_F7_PRESS    405
#define IDD_DIALOG_INDEX_PROMPT         408
#define IDR_JPG_MAINFRAME_BKGROUND      409
#define IDD_DIALOG_USERCYCLE_SET        410
#define IDR_MENU_TREND                  416
#define IDR_MENU_OTHER                  417
#define IDR_MENU_DETAIL                 418
#define IDR_MENU_Test                   419
#define IDR_PNG_RECENT_MERCH            420
#define IDR_PNG_TREND_INDEX_DCKO        422
#define IDR_PNG_TREND_INDEX_KCDO        423
#define IDR_PNG_BkBBSLEFT               424
#define IDR_MENU_EMPTY_VIEW             425
#define IDR_PNG_BkBBS                   426
#define IDR_PNG_BkBBSRIGHT              427
#define IDD_DIALOG_CONNECT_SERVER       428
#define IDR_TOOL_ICONS                  429
#define IDB_MENU_BACKGROUND             431
#define IDB_MENU_DOWN                   433
#define IDR_TOOLBAR_GGTONG              438
#define IDB_TOOLBAR_REPORT              440
#define IDB_TOOLBAR_KLINECYLE           441
#define IDB_TOOLBAR_OWNDRAW             442
#define IDD_DIALOG_INDEX_CHOOSE_STOCK   443
#define IDD_DIALOG_OFFLINEDATA          444
#define IDB_TREE_STATE                  446
#define IDC_CUR_OWNDRAW                 447
#define IDD_DIALOG_BUDING               448
#define IDD_DIALOG1                     449
#define IDD_DIALOG_MANUAL               449
#define IDD_DIALOG_RESPONSIBILIYT       450
#define IDD_DIALOG_NOTIFY               452
#define IDR_PNG_ZLMM                    455
#define IDD_DIALOG_F10                  456
#define IDR_MENU_F10                    458
#define IDR_MENU_BLOCK_MORE             463
#define IDR_MENU_BLOCK_MORE_DEL         465
#define IDR_PNG_LOGO                    467
#define IDD_DIALOG_TBWND_COLOR          468
#define IDD_DIALOG_SYNC_EXCEL           469
#define IDR_PNG_NET_ON3                 470
#define IDD_DIALOG_COLOR_KLINE          470
#define IDR_PNG_NET_ON4                 471
#define IDD_DIALOG_FORMULA_MANAGER      471
#define IDB_FORMULAR_NEW                472
#define IDD_DIALOG_FORMULAR_PWS         473
#define IDD_DIALOG_TM_STATISTIC         474
#define IDD_DIALOG_MAIN_TIMESALE        476
#define IDR_PNG_TBSPECIAL_START         477
#define IDR_PNG_TBSPECIAL_INDEXBUY      477
#define IDR_PNG_TBSPECIAL_INDEXSELL     478
#define IDR_PNG_TBSPECIAL_COWBEAR       479
#define IDR_PNG_TBSPECIAL_SHORTTRADE    480
#define IDR_PNG_TBSPECIAL_MIDTRADE      481
#define IDR_PNG_TBSPECIAL_CAPITALFLOW   482
#define IDR_PNG_TBSPECIAL_SELECTSTOCK   483
#define IDR_PNG_TBSPECIAL_HOTGOLD       484
#define IDR_PNG_TBSPECIAL_MAJORRANK     485
#define IDR_PNG_TBSPECIAL_HOTFORCE      486
#define IDD_DIALOG_QR_CODE              488
#define IDR_PNG_TBSPECIAL_END           497
#define IDD_DIALOG_BELONGBLO            499
#define IDR_MENU_PRICE                  500
#define IDC_CURSOR1                     501
#define IDI_ICON_FOLDER                 502
#define IDD_DIALOG_INPUT_SHOWSTRING     504
#define IDD_DIALOG_NET_FLOW             505
#define IDD_DIALOG_NOTEPAD              508
#define IDD_DIALOG_NEWNOTE              509
#define IDD_DIALOG_ADDTOBLOCK           510
#define IDD_DIALOG_REMOVEFROMBLOCK      511
#define IDD_DIALOG_CHOOSESTOCK          512
#define IDB_BITMAP_CHOUMA               515
#define IDD_DIALOG_CHOUMA               516
#define IDD_DIALOG2                     517
#define IDR_PNG_EXPERT                  518
#define IDR_MENU_REPORT_NEW             519
#define IDD_DIALOG_DOWNLOAD             520
#define IDD_DIALOG_PHASESORT            521
#define IDD_DIALOG_IE                   522
#define IDD_DIALOG_CUSTOM_STOCK         523
#define IDD_DIALOG_CUSTOM_CONDITION     524
#define IDD_DIALOG_INTERVAL_KLINE       525
#define IDD_DIALOG_INTERVAL_TREDN       526
#define IDB_BITMAP_TRAND_INTERVAL       527
#define IDD_DIALOG_MARK_TEXT            528
#define IDD_DIALOG_MARK_MANAGER         529
#define IDD_DIALOG_MARKETRADAR          530
#define IDD_DIALOG_MARKETRADAROPTION    531
#define IDD_DIALOG_MARKETRADARETC       532
#define IDD_DIALOG_MARKETRADARSETTING   533
#define IDB_BITMAP_STATUSBAR_DUOKONG    534
#define IDD_DIALOG_ALARM_SET            535
#define IDD_DIALOG_ALARM_MODIFY         536
#define IDD_DIALOG_ALARM_FORMULAR       537
#define IDR_MENU_TICK                   540
#define IDD_DIALOG_ZHONGCANGCHIGU       541
#define IDD_DIALOG_ARBITRAGE            542
#define IDD_DIALOG_ARBITRAGE_FORMULAR   543
#define IDR_MENU_REPORT_ARBITRAGE       544
#define IDR_PNG_TRADEBUY                548
#define IDR_PNG_TRADESALE               550
#define IDD_DIALOG_TRADE                551
#define IDD_DIALOG_HIS_TIMESELECT       552
#define IDR_PNG_UP                      553
#define IDR_PNG_DOWN                    554
#define IDR_MENU_HOLD                   555
#define IDD_DIALOG_TRADELOGIN           555
#define IDR_MENU_ORDER                  556
#define IDD_DIALOG_TRADEBIDCONTAINER    557
#define IDD_DIALOG_FOREX                558
#define IDR_MENU_ORDER1                 558
#define IDD_DIALOG_FOREX_OPMODE         559
#define IDB_BITMAP_FOREX_GRID           560
#define IDD_DIALOG_FOREXORDERSCHEDULE   561
#define IDD_DIALOG_LOGINTRADE           562
#define IDC_CUR_FOREX_TRADE             563
#define IDC_CUR_DRAG_MERCH              565
#define IDD_DIALOG_ARBITRAGE_SEL        566
#define IDD_DIALOG_FILE_CHOOSE          567
#define IDD_DIALOG_NEWSVIEW             568
#define IDD_DIALOG_NETWORK_SET          569
#define IDR_PNG_BULB_ON                 570
#define IDR_PNG_BULB_BLUE               570
#define IDR_PNG_BULB_OFF                571
#define IDR_PNG1                        572
#define IDD_DIALOG_TODAYCOMMENT         573
#define IDD_DIALOG_TODAYCOMMENT_IE      573
#define IDD_DIALOG_RESTOREWKSPACE       574
#define IDD_DIALOG_TRADEQUERY           575
#define IDR_PNG_BLUE_RED                576
#define IDD_DIALOG_IM                   579
#define IDR_PNG_MESSAGE                 581
#define IDD_DIALOG_OPEN                 581
#define IDR_PNG_MESSAGE_HIDE            582
#define IDD_DIALOG_CLOSE                582
#define IDD_DIALOG_ADVERTISE            583
#define IDD_DIALOG_TIP                  584
#define IDB_BITMAP_OPENU                584
#define IDB_BITMAP_OPEND                585
#define IDI_ICON_HELP                   585
#define IDI_ICON_OPEN1                  586
#define IDD_DIALOG_PULLDOWN             586
#define IDI_ICON_OPEN2                  587
#define IDR_MENU_WSPSET                 587
#define IDI_ICON_CLOSE1                 590
#define IDR_MENU_WND                    590
#define IDI_ICON_CLOSE2                 591
#define IDR_PNG_COMMSTATUSBAR           591
#define IDI_ICON_CANCEL1                592
#define IDD_DIALOG_NEW_LOGIN            592
#define IDB_BITMAP_BUSER                593
#define IDI_ICON_CANCEL2                594
#define IDB_BITMAP_BPASSWORD            594
#define IDI_ICON_REFRESH1               595
#define IDI_ICON_REFRESH2               596
#define IDD_DIALOG_JP_NEWS              596
#define IDI_ICON_SHOW1                  597
#define IDB_TABBK_NEWS                  597
#define IDI_ICON_SHOW2                  598
#define IDI_ICON_HIDE1                  599
#define IDR_PNG_MENUICON                599
#define IDI_ICON_HIDE2                  600
#define IDI_ICON_ACCOUNT_LEFT1          601
#define IDB_BITMAP_MENUICO              601
#define IDI_ICON_OPEN_LEFT1             602
#define IDD_DIALOG_EDIT_REPORT          602
#define IDD_DIALOG_WELCOME              603
#define IDD_DIALOG_INDEX_HELP           604
#define IDD_DIALOG_SIMULATION_HOMEPAGE  605
#define IDI_ICON_CONNECT_BLACK          610
#define IDI_ICON_CONNECT_COLOR          611
#define IDI_ICON_REFRESH_BLACK          612
#define IDI_ICON_REFRESH_COLOR          613
#define IDI_ICON_FOLD_BLACK             614
#define IDI_ICON_FOLD_COLOR             615
#define IDB_BITMAP_LOG_PIC              616
#define IDI_ICON_QUIT_BLACK             616
#define IDI_ICON_SUC                    617
#define IDD_DIALOG_CLOSETRADETIP        617
#define IDI_ICON_ERR                    618
#define IDI_ICON_TIP                    619
#define IDI_ICON_WAR                    620
#define IDI_ICON_UNENABLE_CLOSE         621
#define IDI_ICON_CLOSETRADETIP          622
#define IDB_VERTICAL_SCROLLBAR_CHANNEL_BACAI 623
#define IDI_ICON_QUIT_COLOR             623
#define IDB_VERTICAL_SCROLLBAR_DOWNARROW_BACAI 624
#define IDD_DIALOG_CHANGE_PASSWORD      624
#define IDB_VERTICAL_SCROLLBAR_THUMB_BACAI 625
#define IDB_VERTICAL_SCROLLBAR_THUMB_NO_COLOR_BACAI 626
#define IDB_VERTICAL_SCROLLBAR_UPARROW_BACAI 627
#define IDI_ICON_LOGOUT_LEFT1           628
#define IDB_BITMAP_ARROW                629
#define IDI_ICON_CLOSEWND1              630
#define IDR_PNG_SPIN_ADD                631
#define IDI_ICON_CLOSEWND2              632
#define IDR_PNG_SPIN_SUB                633
#define IDR_PNG_TRADE_MAX               634
#define IDR_PNG_CLOSE_BLACK             635
#define IDR_PNG_CLOSE_COLOR             636
#define IDR_PNG_REMOVE_BLACK            637
#define IDR_PNG_REMOVE_COLOR            638
#define IDR_PNG_SEARCH_BLACK            639
#define IDR_PNG_TRADE_CHECK             640
#define IDR_PNG_TRADE_UCHECK            641
#define IDR_PNG_BUY_OK                  642
#define IDR_PNG_SELL_OK                 643
#define IDR_PNG_OPEN_BLACK              644
#define IDR_PNG_OPEN_COLOR              645
#define IDI_ICON_QUICKORDER_CLOSE1      646
#define IDR_PNG_SEARCH_COLOR            646
#define IDI_ICON_QUICKORDER_CLOSE2      647
#define IDR_PNG_ACCOUNTINFO_BLACK       647
#define IDR_PNG_ACCOUNTINFO_COLOR       648
#define IDR_PNG_GOODS_BLACK             649
#define IDD_DIALOG_QUICKORDER           650
#define IDR_PNG_GOODS_COLOR             650
#define IDB_BITMAP_QUICKORDER_BK        651
#define IDR_PNG_MODIFYPW_BLACK          651
#define IDI_ICON_QUICKORDER_ADD1        652
#define IDR_PNG_MODIFYPW_COLOR          652
#define IDI_ICON_QUICKORDER_ADD2        653
#define IDI_ICON_QUICKORDER_SUB1        654
#define IDI_ICON_QUICKORDER_SUB2        655
#define IDR_MENU_HISTORY                656
#define IDR_PNG_MENU_FOLD_COLOR         660
#define IDR_PNG_MENU_EXPAND_COLOR       661
#define IDR_PNG_RADIOBUY                662
#define IDR_PNG_RADIOSELL               663
#define IDB_BITMAP_TRADE_HSCROLL        664
#define IDB_BITMAP_TRADE_VSCROLL        666
#define IDD_DIALOG3                     667
#define IDB_BITMAP_TRADE_SCROLLBAR_CHANNEL 668
#define IDI_ICON_EXPAND_BLACK           669
#define IDI_ICON_EXPAND_COLOR           670
#define IDC_CUR_HAND                    671
#define IDR_PNG_MENU_EXPAND_BLACK       672
#define IDR_PNG_MENU_FOLD_BLACK         673
#define IDB_BITMAP_TRADE_USER           674
#define IDB_BITMAP_TRADE_PWD            675
#define IDB_BITMAP_TRADE_YZM            676
#define IDD_DIALOG_EXPORT_SALE_DATA     677
#define IDR_MENU2                       679
#define IDR_MENU_TIMESALE               679
#define IDB_BITMAP_SUB                  680
#define IDB_BITMAP_QUICK_ORDER_RED      687
#define IDB_BITMAP_QUICK_ORDER_GREEN    688
#define IDB_BITMAP_QUICK_ORDER_SUB      689
#define IDB_BITMAP2                     690
#define IDB_BITMAP_QUICK_ORDER_ADD      690
#define IDB_BITMAP_QUICK_ORDER__BK_TITLE 691
#define IDB_BITMAP_QUICK_ORDER_ICON     692
#define IDB_BITMAP1                     693
#define IDB_BITMAP_QUICK_ORDER_CLOSE    693
#define IDR_MENU_QRCODE                 694
#define IDI_ICON_HOME_BLACK             695
#define IDD_DIALOG4                     696
#define IDD_DIALOG_QUICKORDER_OPEN      696
#define IDB_BITMAP_QUICK_ORDER_TAB      697
#define IDI_ICON1                       697
#define IDI_ICON_HOME_COLOR             697
#define IDB_BITMAP_QUICK_ORDER_EXIT     698
#define IDD_DIALOG5                     698
#define IDD_DIALOG_USER_ACCOUNT         699
#define IDB_BITMAP_QUICK_ORDER_CHECKBOX 700
#define IDD_DIALOG6                     701
#define IDD_DIALOG_REGISTER             702
#define IDB_PNG_QUICK_ORDER_TITLE_BK    703
#define IDR_TOOLBAR_LEFT                704
#define IDB_PNG_QUICK_ORDER_TITLE_CION  705
#define IDR_TOOLBAR_LEFT1               705
#define IDR_TOOLBAR_RIGHT               705
#define IDD_DIALOG_USERCYCLE_MENU       706
#define IDR_TOOLBAR_LEFT2               706
#define IDR_TOOLBAR_SHORT_CUT           706
#define IDR_TOOLBAR_SHORTCUT            706
#define IDB_PNG_QUICK_ORDER_SUB         707
#define IDD_DIALOG_USER_GUIDE           708
#define IDB_PNG_QUICK_ORDER_ADD         709
#define IDB_BITMAP3                     710
#define IDB_PNG_QUICK_ORDER_RED         711
#define IDB_PNG_QUICK_ORDER_GREENIDB_PNG3 712
#define IDB_PNG_QUICK_ORDER_GREEN       713
#define IDR_MENU_INDEX                  714
#define IDB_PNG_FULL_SCREEN             715
#define IDD_DIALOG_TRADE_SETUP          715
#define IDB_PNG_SEARCH                  716
#define IDB_SCREEN_BACK                 717
#define IDD_DIALOG_ECONOMIC_TIP         718
#define IDB_PNG_SEARCH_BK               718
#define IDD_DIALOG_ECONOMIC_DATA        719
#define IDB_PNG_ZHENGDANGSHI            719
#define IDD_DIALOG_QUANT_KLINE          720
#define IDD_DIALOG_DIALY                721
#define IDD_DIALOG_PUSH_MESSAGE         722
#define IDB_PNG_KLINE_SET               724
#define IDD_DIALOG8                     725
#define IDD_DIALOG_NEW_COMMENT          726
#define IDR_PNG_REPORT_H                726
#define IDD_DIALOG_SLOGON               727
#define IDD_DIALOG_SLOGAN_EXIT          727
#define IDR_PNG_REPORT_B                727
#define IDD_DIALOG_TRADE_DOWNLOAD       728
#define IDR_PNG_REPORT_S                728
#define IDD_DIALOG_TRADE_SETTING        729
#define IDR_PNG_REPORT_U                729
#define IDD_DIALOG_TRADESETTING_DATA    730
#define IDR_PNG_REPORT_ZIXUAN           730
#define IDR_PNG_REPORT_ADDZIXUAN        731
#define IDB_PNG_KLINE_FULL              733
#define IDB_PNG_KLINE_RESTORE           734
#define IDB_BITMAP4                     735
#define IDB_PNG8                        736
#define IDB_PNG_LEFTBAR                 736
#define IDB_PNG_STRATEGY_BUY            737
#define IDB_PNG_STRATEGY_MUL            738
#define IDB_PNG_STRATEGY_SELL           739
#define IDD_DIALOG7                     740
#define IDD_DIALOG_STATEGY_INFO         740
#define IDD_DIALOG_IMP_USERBLOCK_DISPLAY 804
#define IDD_DIALOG_IMP_USERBLOCK        805
#define IDD_DIALOG_BLOCK_MAG1           806
#define IDD_DIALOG_BLOCK_ADD            806
#define IDD_DIALOG_WEB_CONTENT          807
#define IDC_TAB1                        1000
#define IDC_CHECK_FS                    1001
#define IDC_CHECK_TRADE                 1002
#define IDC_LIST_IOVIEW                 1003
#define IDC_CHECK_MINIUTE1              1004
#define IDC_CHECK_MINIUTE15             1005
#define IDC_CHECK_MINIUTE30             1006
#define IDC_IOVIEW_INFO                 1007
#define IDC_CHECK_MINIUTE60             1008
#define IDC_EDIT_INPUTINFO              1009
#define IDC_CHECK_MINIUTE_USER          1009
#define IDC_CHECK_MINIUTE5              1010
#define IDC_CHECK_WEEK                  1011
#define IDC_BUTTON_ZSPLIT               1012
#define IDC_CHECK_DAY                   1012
#define IDC_CHECK_MONTH                 1013
#define IDC_BUTTON_HSPLIT               1014
#define IDC_CHECK_MINIUTE180            1014
#define IDC_CHECK_QUARTER               1015
#define IDC_BUTTON_SAVE                 1016
#define IDC_CHECK_HALFYEAR              1017
#define IDC_BUTTON_ANALYZE              1017
#define IDC_BUTTON_STOP                 1017
#define IDC_BUTTON_IMPORT               1018
#define IDC_BUTTON_SETTING              1018
#define IDC_CHECK_YEAR                  1019
#define IDC_RADIO_TOP                   1020
#define IDC_CHECK_DAY_USER              1020
#define IDC_CHECK_YEAR2                 1021
#define IDC_CHECK_MINIUTE240            1021
#define IDC_RADIO_BOTTOM                1022
#define IDC_RADIO_LEFT                  1023
#define IDC_EDIT21                      1024
#define IDC_RADIO_RIGHT                 1025
#define IDC_EDIT31                      1026
#define IDC_BUTTON_TEST                 1026
#define IDC_RADIO_NONE                  1027
#define IDC_COMBO_HOST2                 1027
#define IDC_ZTDJ                        1028
#define IDC_BUTTON_DEL                  1029
#define IDC_FT                          1030
#define IDC_BUTTON_OFTEN                1030
#define IDC_BUTTON_CLEARNOTES           1030
#define IDC_BUTTON_ADDTAB               1031
#define IDC_BUTTON_OFTEN2               1031
#define IDC_BUTTON_FLOAT                1031
#define IDC_EDIT41                      1032
#define IDC_BUTTON_EXPORT               1032
#define IDC_BUTTON_HIDE                 1032
#define IDC_EDIT32                      1033
#define IDC_BUTTON_CLOSE                1033
#define IDC_EDIT12                      1034
#define IDC_BUTTON_USER_EXPORT          1034
#define IDC_CHECK_CHOOSE                1035
#define IDC_EDIT_LINE1                  1035
#define IDC_EDIT42                      1036
#define IDC_EDIT22                      1037
#define IDC_EDIT13                      1038
#define IDC_EDIT23                      1039
#define IDC_EDIT33                      1040
#define IDC_STATIC_BUY                  1041
#define IDC_EDIT_LINE2                  1041
#define IDC_EDIT43                      1042
#define IDC_EDIT14                      1043
#define IDC_EDIT24                      1044
#define IDC_EDIT34                      1045
#define IDC_EDIT44                      1046
#define IDC_COMBO1                      1047
#define IDC_EDIT_LINE3                  1047
#define IDC_LIST1                       1048
#define IDC_EDIT15                      1048
#define IDC_COMBO2                      1048
#define IDC_COMBO_LOGTYPE               1049
#define IDC_EDIT25                      1049
#define IDC_COMBO3                      1049
#define IDC_LIST_BLOCK_SELECTED         1049
#define IDC_LIST_NOW                    1049
#define IDC_BUTTON_NORMALFONT           1050
#define IDC_EDIT35                      1050
#define IDC_COMBO4                      1050
#define IDC_LIST_ALL                    1051
#define IDC_EDIT45                      1051
#define IDC_BUTTON_SMALLFONT            1052
#define IDC_EDIT_LINE4                  1052
#define IDC_LIST_USER                   1052
#define IDC_BUTTON_FONT_RESET           1053
#define IDC_EDIT_LINE5                  1053
#define IDC_BUTTON_COLOR                1054
#define IDC_EDIT_LINE6                  1054
#define IDC_STATIC_RISE                 1055
#define IDC_EDIT_LINE7                  1055
#define IDC_EDIT_LINE_EX1               1056
#define IDC_EDIT_AUTO_CHANGEPAGE        1057
#define IDC_EDIT_LINE_EX2               1057
#define IDC_CSGS                        1058
#define IDC_EDIT_REFRESH                1059
#define IDC_EDIT_LINE_EX3               1059
#define IDC_INPUT                       1060
#define IDC_EDIT_REFRESH_STATESBAR      1061
#define IDC_EDIT_LINE_EX4               1061
#define IDC_DYHS                        1062
#define IDC_STATIC_YELLOW               1063
#define IDC_EDIT_1                      1064
#define IDC_NAME                        1065
#define IDC_STATIC_BLUE                 1066
#define IDC_EDIT_2                      1067
#define IDC_EDIT11                      1068
#define IDC_STATIC_GRIDSELECTED         1069
#define IDC_EDIT_AUTO_CHANGEPAGE6       1070
#define IDC_STATIC_BACKGROUND           1071
#define IDC_EDIT_AUTO_CHANGEPAGE7       1072
#define IDC_STATIC_GRIDLINE             1073
#define IDC_EDIT_AUTO_CHANGEPAGE8       1074
#define IDC_STATIC_KEEP                 1075
#define IDC_STATIC_TEXT                 1076
#define IDC_STATIC_AMOUNT               1077
#define IDC_STATIC_VOLUME               1078
#define IDC_STATIC_MAGENTA              1079
#define IDC_STATIC_CADETBLUE            1080
#define IDC_STATIC_GREENYELLOW          1081
#define IDC_STATIC_PURPLE               1082
#define IDC_STATIC_DODGERBLUE           1083
#define IDC_STATIC_PINK                 1085
#define IDC_STATIC_CHARTAXISLINE        1086
#define IDC_STATIC_NAVYBLUE             1087
#define IDC_STATIC_SKYBLUE              1088
#define IDC_STATIC_FALL                 1089
#define IDC_STATIC_PREVIEW              1090
#define IDC_LIST                        1091
#define IDC_STATIC_COLOR                1092
#define IDC_BUTTON_SET                  1093
#define IDC_BUTTON_BIGFONT              1094
#define IDC_BUTTON_REG222               1094
#define IDC_TAB_GRIDHEAD                1095
#define IDC_EDIT_NAME                   1097
#define IDC_EDIT_ADDRESS                1098
#define IDC_EDIT_HOSTNAME               1099
#define IDC_LIST_EXIST                  1100
#define IDC_EDIT_PASSWORD               1101
#define IDC_EDIT_HOSTADDRESS            1102
#define IDC_EDIT_AUTHENTICATE           1102
#define IDC_EDIT_HOTKEY                 1103
#define IDC_BUTTON_ADD                  1104
#define IDC_EDIT_HOSTPORT               1105
#define IDC_LIST_EXIST2                 1106
#define IDC_BUTTON_UP                   1107
#define IDC_BUTTON_DOWN                 1108
#define IDC_BUTTON_CONNECT              1109
#define IDC_BUTTON_UNCONNECT            1110
#define IDC_CHECK_SAVEPASSWORD          1111
#define IDC_BUTTON_CANCEL               1112
#define IDC_COMBO_HOST                  1113
#define IDC_CHECK1                      1114
#define IDC_CHECK_OPTIMIZE_SERVER       1114
#define IDC_BUTTON_ADD1                 1115
#define IDC_CHECK2                      1115
#define IDC_COMBO_HOSTTRADE             1115
#define IDC_CHECK_REM_USER              1115
#define IDC_BUTTON_MODIFY1              1116
#define IDC_CHECK3                      1116
#define IDC_BUTTON_ADD2                 1117
#define IDC_CHECK7                      1117
#define IDC_COMBO_ENV                   1117
#define IDC_BUTTON_MODIFY2              1118
#define IDC_CHECK8                      1118
#define IDC_CHECK_PROXY                 1119
#define IDC_CHECK9                      1119
#define IDC_RADIO_SOCK4                 1120
#define IDC_CHECK10                     1120
#define IDC_RADIO_SOCK5                 1121
#define IDC_CHECK11                     1121
#define IDC_RADIO_HTTP                  1122
#define IDC_CHECK12                     1122
#define IDC_EDIT_PORT                   1123
#define IDC_CHECK13                     1123
#define IDC_EDIT_PROXY_NAME             1124
#define IDC_CHECK14                     1124
#define IDC_EDIT_PROXY_PWD              1125
#define IDC_EDIT_FUNC_SELECT            1126
#define IDC_CHECK15                     1127
#define IDC_BUTTON_REGISTER             1128
#define IDC_CHECK16                     1128
#define IDC_BUTTON1                     1129
#define IDC_BUTTON_NEW                  1129
#define IDC_BUTTON_DELETE1              1129
#define IDC_BUTTON_NAME                 1129
#define IDC_BUTTON_DEFAULT              1129
#define IDC_BUTTON_PROMPT               1129
#define IDC_BUTTON_START                1129
#define IDC_BUTTON_ADD_ALL              1129
#define IDC_BUTTON_CLEAR                1129
#define IDC_BUTTON_RECEHCK              1129
#define IDC_BUTTON_PAUSE                1129
#define IDC_BUTTON_SWITCH               1129
#define IDC_BUTTON_BLOCKNEW             1129
#define IDC_BUTTON_SEL_ALL              1129
#define IDC_BUTTON_TABCTL               1129
#define IDC_BUTTON_OFFLINE              1129
#define IDC_BUTTON_INTERVAL_SORT        1129
#define IDC_BUTTON_CHANGE               1129
#define IDC_BUTTON_ADDTOBLOCK           1129
#define IDC_BUTTON_OPENCLOSE            1129
#define IDC_BUTTON_ADD_STOCK            1130
#define IDC_BUTTON_CODE                 1130
#define IDC_BUTTON_DEL_ALL              1130
#define IDC_BUTTON_RESET                1130
#define IDC_BUTTON_NEWNOTE              1130
#define IDC_BUTTON_BLOCKDEL             1130
#define IDC_BUTTON_UNSEL_ALL            1130
#define IDC_BUTTON_REMOVE               1130
#define IDC_BUTTON5                     1130
#define IDC_BUTTON_ADD_BLOCK            1131
#define IDC_BUTTON6                     1131
#define IDC_BUTTON_LEFT                 1132
#define IDC_BUTTON_REMOVEALL            1132
#define IDC_TREE_BLOCK                  1133
#define IDC_CHECK_PASSWORD              1134
#define IDC_TREE_BLOCK2                 1134
#define IDC_BUTTON_MODIFY               1135
#define IDC_BUTTON_DEL_BLOCK            1136
#define IDC_BUTTON_EDIT_BLOCK           1137
#define IDC_TREE1                       1138
#define IDC_BUTTON_CONFIRM              1139
#define IDC_BUTTON_SAVE_BLOCK           1140
#define IDC_BUTTON_ADD_MERCH            1141
#define IDC_EXPLAINBRIEF                1142
#define IDC_BUTTON_DEL_MERCH            1143
#define IDC_MYHELP                      1144
#define IDC_EDIT_WIDTH                  1145
#define IDC_SPIN_WIDTH                  1146
#define IDC_PASSWORD                    1147
#define IDC_EDIT_NUM                    1148
#define IDC_SPIN_NUM                    1149
#define IDC_LIST_MERCH                  1150
#define IDC_LIST_SHOW                   1151
#define IDC_LIST_MERCH_SELECT           1151
#define IDC_LIST_FORMULAR               1151
#define IDC_CHECK_OPENLAST              1152
#define IDC_LIST_ARBITRAGE              1153
#define IDC_BUTTON_RIGHT                1154
#define IDC_COMBO_GROUP                 1155
#define IDC_BUTTON_CAN_USED             1156
#define IDC_PROGRESS                    1157
#define IDC_STATIC_SHOW                 1158
#define IDC_STATIC_PROMPT               1159
#define IDC_PROGRESS_LOGIN              1160
#define IDC_STATIC_PROMPT3              1160
#define IDC_RICHEDIT1                   1161
#define IDC_RICHEDIT                    1161
#define IDC_STATIC_PROMPT2              1161
#define IDC_STATIC_PROMPT4              1161
#define IDC_STATIC_PROMPT5              1162
#define IDC_LIST_WSP                    1202
#define IDC_EDIT1                       1209
#define IDC_CHECK_BETRANSPARENT         1210
#define IDC_EDIT2                       1210
#define IDC_COMBO                       1211
#define IDC_EDIT3                       1211
#define IDC_EDIT                        1212
#define IDC_EDIT_DAYB                   1212
#define IDC_EDIT_STABILITY              1212
#define IDC_EDIT_TIME_END               1212
#define IDC_EDIT4                       1212
#define IDC_STATIC_GRID                 1213
#define IDC_EDIT_MONTHE                 1213
#define IDC_EDIT_STRONG                 1213
#define IDC_EDIT_OPEN                   1213
#define IDC_EDIT7                       1213
#define IDC_CUSTOM_TRACE                1214
#define IDC_EDIT_DAYE                   1214
#define IDC_EDIT_WEEK                   1214
#define IDC_EDIT_HIGH                   1214
#define IDC_STATIC_SHOWLOG              1215
#define IDC_EDIT_LOW                    1215
#define IDC_EDIT_CLOSE                  1216
#define IDC_EDIT_VOLUMN                 1217
#define IDC_EDIT1_AMOUNT                1218
#define IDC_EDIT_COUNT_TICK             1218
#define IDC_EDIT1_AVGPRICE              1219
#define IDC_LIST_CONDITION              1220
#define IDC_EDIT_RISE_RATE              1220
#define IDC_STATIC_PARAMPRE             1221
#define IDC_EDIT_SHAKE_RATE             1221
#define IDC_STATIC_PARAMAFT             1222
#define IDC_EDIT_CHANGE                 1222
#define IDC_EDIT_SELL                   1222
#define IDC_EDIT_PARAM                  1223
#define IDC_EDIT_WAI                    1223
#define IDC_EDIT_ATTACK_COUNT           1223
#define IDC_EDIT_CODE                   1225
#define IDC_EDIT_SUCCESS_RATE           1225
#define IDC_CHECK_ONOFF                 1227
#define IDC_EDIT_VALUE                  1228
#define IDC_COMBO_SEL_CONDITION         1230
#define IDC_RADIO_AND                   1232
#define IDC_RADIO_OR                    1233
#define IDC_MONTHCALENDAR2              1235
#define IDC_MONTHCALENDAR3              1236
#define IDC_EDIT_TOTAL                  1237
#define IDC_EDIT_RESULT                 1238
#define IDC_BUTTON_ADDTO                1239
#define IDC_BUTTON_DO                   1240
#define IDC_COMBO_CYCLE                 1242
#define IDC_LIST_BLOCKALL               1244
#define IDC_STATIC_PRE                  1245
#define IDC_EDIT_YEARB                  1247
#define IDC_EDIT_YEARE                  1248
#define IDC_EDIT_MONTHB                 1249
#define IDC_STATIC_MSG                  1252
#define IDC_STATIC_AFT                  1253
#define IDC_EDIT_PARAM2                 1254
#define IDC_STATIC_PRE2                 1255
#define IDC_STATIC_PRE3                 1256
#define IDC_STATIC_AFT2                 1257
#define IDC_STATIC_AFT3                 1258
#define IDC_EDIT_PARAM3                 1259
#define IDC_RADIO1                      1260
#define IDC_EDIT_PARAM4                 1260
#define IDC_RADIO2                      1261
#define IDC_RADIO3                      1262
#define IDC_COMBO_HEAD                  1262
#define IDC_RADIO4                      1263
#define IDC_CHECK                       1263
#define IDC_RADIO5                      1264
#define IDC_BUTTON_DELTAB               1265
#define IDC_RADIO_SHAKERATE             1265
#define IDC_RADIO6                      1265
#define IDC_RADIO7                      1266
#define IDC_DATETIMEPICKER_BEGIN_YMD    1269
#define IDC_DATETIMEPICKER_BEGIN_HMS    1270
#define IDC_DATETIMEPICKER_END_YMD      1271
#define IDC_DATETIMEPICKER_END_HMS      1272
#define IDC_RADIO_1                     1273
#define IDC_RADIO_2                     1274
#define IDC_RADIO_0                     1276
#define IDC_EDIT_GRIDRECT               1278
#define IDC_EDIT_MA5                    1280
#define IDC_EDIT_MA8                    1281
#define IDC_EDIT_MA13                   1282
#define IDC_EDIT_CONDITION5_KLINENUM    1283
#define IDC_EDIT_CONDITION5_TIMES       1284
#define IDC_EDIT_INTENSITYOC            1285
#define IDC_EDIT_MA5QZ                  1286
#define IDC_EDIT_MA8QZ                  1287
#define IDC_EDIT_MA13QZ                 1288
#define IDC_CHECK_CDT5                  1289
#define IDC_CHECK_CDT4                  1290
#define IDC_CHECK_CDT3                  1291
#define IDC_CHECK_CDT2                  1292
#define IDC_RADIO_3                     1293
#define IDC_STATIC1                     1294
#define IDC_STATIC2                     1295
#define IDC_BUTTON_BEGIN                1296
#define IDC_EDIT_PARAM1                 1297
#define IDC_BUTTON_EXIT                 1298
#define IDC_STATIC_OWN1                 1299
#define IDC_STATIC_OWN2                 1300
#define IDC_EDIT_OWN                    1301
#define IDC_PROGRESS_CALC_INDEX         1302
#define IDC_STATIC_PROGRESS_CALC        1303
#define IDC_STATIC_A                    1304
#define IDC_STATIC_B                    1305
#define IDC_STATIC_C                    1306
#define IDC_CHECK_PROMPT                1307
#define IDC_PROGRESS_INDEX_CHOOSE_STOCK2 1307
#define IDC_PROGRESS_REQ_WEIGHT         1307
#define IDC_STATIC_PROGRESS_WEIGHT      1308
#define IDC_STATIC_PROGRESS_KLINE       1309
#define IDC_STATIC_VERSION              1309
#define IDC_PROGRESS_INDEX_CHOOSE_STOCK3 1310
#define IDC_PROGRESS_DOWN_KLINE         1310
#define IDC_STATIC_LMTIME               1310
#define IDC_STATIC_KLINENUMS            1311
#define IDC_BUTTON2                     1312
#define IDC_BUTTON_BLOCKMODIFY          1312
#define IDC_BUTTON_BEIGN                1312
#define IDC_BUTTON_CHANGEMERCH          1312
#define IDC_BUTTON_CHANGE_MERCH         1312
#define IDC_BUTTON_BLOCK_SORT           1312
#define IDC_BUTTON_MODIFYMARK           1312
#define IDC_BUTTON3                     1313
#define IDC_BUTTON_DEL_ALL_MERCH        1313
#define IDC_BUTTON_SELALL               1313
#define IDC_BUTTON_CONFIRM_PWD          1313
#define IDC_BUTTON4                     1314
#define IDC_COMBO_NETYPE                1314
#define IDC_BUTTON_ADD_TO               1314
#define IDC_BUTTON_UNSELALL             1314
#define IDC_BTN_NETTEST                 1314
#define IDC_STATIC_CLOSE_POS            1315
#define IDC_COMBO_ITEM                  1315
#define IDC_TREE_MERCH                  1315
#define IDC_COMBO_WSP                   1316
#define IDC_RADIO_ALL                   1316
#define IDC_STATIC_INNER                1317
#define IDC_RADIO_GROUP                 1317
#define IDC_RADIO_SYS                   1318
#define IDC_RADIO_USER                  1319
#define IDC_STATIC_LOGIN_TEXT_START     1320
#define IDC_TREE_GROUP                  1320
#define IDC_STATIC_HOST                 1321
#define IDC_TREE_SYS                    1321
#define IDC_STATIC_NAME                 1322
#define IDC_STATIC_PWD                  1323
#define IDC_STATIC_WSP                  1324
#define IDC_STATIC_Y                    1324
#define IDC_STATIC_HOST2                1324
#define IDC_STATIC_Y2                   1325
#define IDC_STATIC_AUTHEN               1325
#define IDC_LIST_BL_RIGHT               1326
#define IDC_LIST_BL_LEFT                1327
#define IDC_CHECK_CHANGE_SEL            1328
#define IDC_STATIC_VERSIONNAME          1329
#define IDC_STATIC_LOGIN_TEXT_END       1330
#define IDC_STATIC_COPYRIGHT            1330
#define IDC_STATIC_TIP                  1331
#define IDC_LIST_HISTORY                1332
#define IDC_STATIC_BEGIN                1333
#define IDC_STATIC_END                  1335
#define ID_HIDE                         1336
#define IDC_STATIC_TEST                 1337
#define IDC_STATIC_SEPARATOR            1338
#define IDC_STATIC_TITLE                1339
#define IDC_STATIC_SEPARATOR2           1339
#define IDC_EDIT_TITLE                  1340
#define IDC_RADIO_SUN                   1341
#define IDC_CHECK_ALL_MERCH             1342
#define IDC_RADIO_CLOUD                 1342
#define IDC_CHECK_REALTIME              1343
#define IDC_RADIO_RAIN                  1343
#define IDC_RADIO_DAY                   1344
#define IDC_RADIO_SNOW                  1344
#define IDC_RADIO_5MIN                  1345
#define IDC_RADIO_1MIN                  1346
#define IDC_DATETIMEPICKER1             1346
#define IDC_RADIO_F10                   1347
#define IDC_DATETIMEPICKER2             1347
#define IDC_DATETIMEPICKER_BEGIN        1348
#define IDC_LIST2                       1348
#define IDC_PROGRESS_PROMPT             1349
#define IDC_RADIO_PINGJUN               1349
#define IDC_DATETIMEPICKER_END          1350
#define IDC_RADIO_SANJIAO               1350
#define IDC_EDIT_ATTENUATION            1351
#define IDC_RADIO_MONTH                 1351
#define IDC_EDIT_DEFAULTTRADERATE       1352
#define IDC_EDIT_CYCLE                  1353
#define IDC_STATIC_BMP                  1354
#define IDC_STATIC_COUNTRY_ICON         1355
#define IDC_STATIC_PARAM1               1358
#define IDC_STATIC_PARAM2               1359
#define IDC_STATIC_PARAM3               1360
#define IDC_STATIC_PARAM4               1361
#define IDC_RADIO_P1                    1362
#define IDC_RADIO_P2                    1363
#define IDC_RADIO_P3                    1364
#define IDC_RADIO_P4                    1365
#define IDC_PROGRESS1                   1366
#define IDC_STATIC_RANGE1               1367
#define IDC_STATIC_RANGE2               1368
#define IDC_STATIC_RANGE3               1369
#define IDC_STATIC_RANGE4               1370
#define IDC_LIST_MERCHS                 1371
#define IDC_LIST_VALUE                  1372
#define IDC_EDIT_MERCHS_ALL             1373
#define IDC_EDIT_MERCHS_CHOOSE          1374
#define IDC_RADIO_VALUE                 1375
#define IDC_COMBO_CMP                   1376
#define IDC_STATIC_POST                 1377
#define IDC_EDIT_TIME_BEGIN             1378
#define IDC_STATIC_NUM                  1379
#define IDC_EDIT_COUNT_MIN              1379
#define IDC_EDIT_AVG_VOLUMN             1380
#define IDC_EDIT_NEI                    1381
#define IDC_EDIT_BUY                    1382
#define IDC_STATIC_V1                   1388
#define IDC_STATIC_V2                   1390
#define IDC_STATIC_V3                   1391
#define IDC_STATIC_V4                   1392
#define IDC_STATIC_V5                   1393
#define IDC_EDIT_LIMIT                  1394
#define IDC_EDIT_BIG_ALL                1395
#define IDC_STATIC_1                    1396
#define IDC_STATIC_2                    1397
#define IDC_STATIC_3                    1398
#define IDC_STATIC_4                    1399
#define IDC_STATIC_5                    1400
#define IDC_STATIC_PIC                  1401
#define IDC_STATIC_6                    1401
#define IDC_LIST_TICK                   1402
#define IDC_STATIC_7                    1402
#define IDC_STATIC_PIC_PAGE3            1403
#define IDC_STATIC_8                    1403
#define IDC_STATIC3                     1404
#define IDC_STATIC_9                    1404
#define IDC_STATIC4                     1405
#define IDC_STATIC_10                   1405
#define IDC_STATIC5                     1406
#define IDC_STATIC6                     1407
#define IDC_STATIC7                     1408
#define IDC_STATIC8                     1409
#define IDC_STATIC9                     1410
#define IDC_STATIC10                    1411
#define IDC_STATIC11                    1412
#define IDC_STATIC12                    1413
#define IDC_STATIC13                    1414
#define IDC_STATIC14                    1415
#define IDC_STATIC16                    1416
#define IDC_STATIC17                    1417
#define IDC_STATIC18                    1418
#define IDC_STATIC19                    1419
#define IDC_STATIC20                    1420
#define IDC_STATIC21                    1421
#define IDC_STATIC22                    1422
#define IDC_STATIC23                    1423
#define IDC_STATIC24                    1424
#define IDC_STATIC25                    1425
#define IDC_RADIO_RISEFALL              1426
#define IDC_RADIO_TRADERATE             1427
#define IDC_RADIO_VOLCAHNGE             1428
#define IDC_RADIO_OFTENBLOCK            1429
#define IDC_RADIO_NORMALBLOCK           1430
#define IDC_CHECK_PREWEIGHT             1431
#define IDC_COMBO_BLOCKLIST             1432
#define IDC_STATIC_DATA                 1433
#define IDC_CHECK0                      1434
#define IDC_EDIT5                       1435
#define IDC_EDIT6                       1436
#define IDC_EDIT8                       1437
#define IDC_CHECK4                      1438
#define IDC_CHECK5                      1439
#define IDC_CHECK17                     1439
#define IDC_EDIT9                       1440
#define IDC_CHECK6                      1441
#define IDC_EDIT_UP                     1442
#define IDC_EDIT_DOWN                   1443
#define IDC_EDIT_CHANGE_RATE            1444
#define IDC_EDIT_RISERATE               1444
#define IDC_EDIT_ETF                    1445
#define IDC_EDIT_CHANGERATE             1445
#define IDC_RADIO8                      1446
#define IDC_EDIT_DAY_RISERATE           1447
#define IDC_EDIT_DAY_FALLRATE           1448
#define IDC_EDIT_5MIN_RISERATE          1449
#define IDC_BUTTON_GET_PWD              1449
#define IDC_EDIT_5MIN_FALLRATE          1450
#define IDC_STATIC_PIE                  1450
#define IDC_STATIC_PIC1                 1452
#define IDC_STATIC_PIC2                 1453
#define IDC_STATIC_PIC3                 1454
#define IDC_STATIC_PIC4                 1455
#define IDC_STATIC_PIC5                 1456
#define IDC_STATIC_PIC6                 1457
#define IDC_STATIC_PIC7                 1458
#define IDC_STATIC_PIC8                 1459
#define IDC_STATIC_PIC9                 1460
#define IDC_STATIC_PIC10                1461
#define IDC_BUTTON_CHOOSEA              1462
#define IDC_BUTTON_CHOOSEB              1463
#define IDC_BUTTON_CHOOSEC              1464
#define IDC_EDIT_FORMULARA              1465
#define IDC_EDIT_FORMULARB              1466
#define IDC_EDIT_FORMULARC              1467
#define IDC_BUTTON_CHANGEA              1468
#define IDC_BUTTON_CHANGEB              1469
#define IDC_BUTTON_CHANGEC              1470
#define IDC_COMBO_ARBITRAGE_TYPE        1471
#define IDC_COMBO_PRICE_TYPE            1472
#define IDC_STATIC_MERCHA               1473
#define IDC_STATIC_MERCHB               1474
#define IDC_STATIC_MERCHC               1475
#define IDC_EDIT_FORMULAR               1476
#define IDC_BUTTON_VALID                1477
#define IDC_CONFIRM                     1478
#define IDC_BUTTON_INSERTMERCH          1478
#define IDC_STATIC_LEFT                 1479
#define IDC_BUTTON_BUY                  1479
#define IDC_EDIT_SAVEDEC                1479
#define IDC_STATIC_ACCOUNT              1480
#define IDC_BUTTON_SELL                 1480
#define IDC_STATIC_MID                  1481
#define IDC_BUTTON_COMMIT               1481
#define IDC_LIST_ARBTRAGE_SEL           1481
#define IDC_STATIC_FOREX                1482
#define IDC_STATIC_ERRMSG               1482
#define IDC_EDIT_TRADEUSER              1482
#define IDC_COMBO_MERCH                 1483
#define IDC_COMBO_TRADESERVER           1483
#define IDC_EDIT_TRADEPWD               1484
#define IDC_EDIT_STOP_FALL              1485
#define IDC_EDIT_VALIDCODE              1485
#define IDC_RADIO_FTM_DEFAULT           1486
#define IDC_EDIT_STOP_RISE              1486
#define IDC_CHECK_SAVEUSER              1486
#define IDC_RADIO_FTM_ONECLICK          1487
#define IDC_EDIT_COMMENT                1487
#define IDC_CHECK_PROTECT               1487
#define IDC_RADIO_FTM_DOUBLECLICK       1488
#define IDC_COMBO_TRADE_TYPE            1488
#define IDC_STATIC_TRADESERVER          1488
#define IDC_COMBO_FTM_BARGAIN           1489
#define IDC_COMBO_ENTRY_ORDER           1489
#define IDC_EDIT_FTM_BARGAIN            1490
#define IDC_EDIT_PRICE                  1490
#define IDC_STATIC_TRADEUSER            1490
#define IDC_SPIN1                       1491
#define IDC_COMBO_VOLUME                1491
#define IDC_SPIN2                       1492
#define IDC_SPIN_STOP_FALL              1492
#define IDC_STATIC_TRADEPWD             1492
#define IDC_SPIN3                       1493
#define IDC_SPIN_STOP_RISE              1493
#define IDC_STATIC_VALIDCODE            1493
#define IDC_COMBO_FTM_ALIVE             1494
#define IDC_CHECK_ALLOW                 1494
#define IDC_CHECK_FTM_STOPLOSE          1495
#define IDC_EDIT_POINT                  1495
#define IDC_COMBO_DM_DIFFNOW_SL         1495
#define IDC_SPIN4                       1496
#define IDC_STATIC_IMMI                 1496
#define IDC_COMBO_FTM_STDYNC            1497
#define IDC_STATIC_ENTRY                1497
#define IDC_EDIT_FTM_STDYNC             1498
#define IDC_STATIC_TYPE                 1498
#define IDC_CHECK_FTM_LIMIT             1499
#define IDC_STATIC_PRICE                1499
#define IDC_EDIT_FTM_LIMIT              1500
#define IDC_STATIC_DATE                 1500
#define IDC_EDIT_FTM_STDISTANCE         1501
#define IDC_STATIC_POINT                1501
#define IDC_EDIT_OVER_DATE              1502
#define IDC_SPIN_ENTRY                  1503
#define IDC_STATIC_POINT_DIF            1504
#define IDC_STATIC_POINT2               1505
#define IDC_EDIT_DM_STOP_FALL           1506
#define IDC_STATIC_SERVER               1507
#define IDC_BUTTON_PRINT                1508
#define IDC_STATIC_SERVER_PROMPT        1509
#define IDC_STATIC_WAIT_RESPONSE        1510
#define IDC_STATIC_WAIT_PROMPT          1511
#define IDC_BUTTON_CANCEL_BILL          1512
#define IDC_BUTTON_CLOSEOUT             1513
#define IDC_BUTTON_LOG                  1514
#define IDC_SPIN_DM_STOP_FALL           1514
#define IDC_EDIT_LOG                    1515
#define IDC_BUTTON_DM_MODIFY            1515
#define IDC_STATIC_SLRANGE              1516
#define IDC_STATIC_SPRANGE              1517
#define IDC_STATIC_NODESC               1518
#define IDC_COMBO_ALLOWDIFF             1519
#define IDC_BUTTON_DM_COPY_SL           1520
#define IDC_STATIC_DM_DIFFNOW_SL        1521
#define IDC_STATIC_DM_DIFFNOW_SP        1522
#define IDC_STATIC_DM_CP_SL             1523
#define IDC_STATIC_DM_CP_SP             1524
#define IDC_STATIC_DM_UNIT_SL           1525
#define IDC_STATIC_DM_UNIT_SL2          1526
#define IDC_TAB_GRID                    1526
#define IDC_STATIC_DM_PRICE_SL          1527
#define IDC_STATIC_DM_UNIT_SP           1528
#define IDC_COMBO_DM_DIFFNOW_SP         1529
#define IDC_BUTTON_DM_COPY_SP           1530
#define IDC_EDIT_DM_STOP_RISE           1531
#define IDC_SPIN_DM_STOP_RISE           1532
#define IDC_STATIC_DM_PRICE_SP          1533
#define IDC_STATIC_DM_UNIT_SP2          1534
#define IDC_STATIC_DM                   1535
#define IDC_STATIC_VERIFY_IMAGE         1535
#define IDC_EDIT_NEWS                   1536
#define IDC_STATIC_PICPOS               1537
#define IDC_COMBO_RUN                   1539
#define IDC_BTN_YES                     1540
#define IDC_BTN_CANCEL                  1541
#define IDC_BTN_PROXYSERVER             1542
#define IDC_GRID                        1544
#define IDC_CHECK_MANUAL                1545
#define IDC_LIST_WKSPACE                1546
#define IDC_EDIT_USER                   1546
#define IDC_EDIT_PWD                    1547
#define IDC_STATIC_TOP                  1548
#define IDC_COMBO_SERVER                1549
#define IDC_STATIC_TIPMSG               1550
#define IDC_STATIC_MIN                  1550
#define IDC_STATIC_INNER2               1551
#define IDC_STATIC_MAX                  1551
#define IDC_SETPRO                      1552
#define IDC_STATIC_DEF                  1552
#define IDC_STATIC_PARAM                1553
#define IDC_BTN_REGISTER2               1554
#define IDC_EDIT_HIDE                   1554
#define IDC_BTN_FGPWD                   1555
#define IDC_BTN_FOCUS                   1555
#define IDC_EDIT_NAME2                  1556
#define IDC_BUTTON_QUICKORDER_SUB       1556
#define IDC_BTN_REG                     1556
#define IDC_BTN_TRAD_LOGIN              1557
#define IDC_BTN_VISITOR_LOGIN           1557
#define IDC_BTN_TP_RIGER                1558
#define IDC_STATIC_SAVE_PWD             1558
#define IDC_STATIC_AUTO_LOGIN           1559
#define IDC_BTN_ADD                     1560
#define IDC_BTN_REG2                    1560
#define IDC_BTN_PASSWORD_RETAKE         1560
#define IDC_BTN_DEL                     1561
#define IDC_BTN_CLEAR                   1562
#define IDC_BTN_OK                      1563
#define IDC_BTN_UP                      1564
#define IDC_BTN_DOWN                    1565
#define IDC_BUTTON_ENTER                1566
#define IDC_BTN_UPLOAD                  1566
#define IDC_STATIC_INITIAL_ASSET        1567
#define IDC_BTN_DOWNLOAD                1567
#define IDC_STATIC_INITIAL_ASSET_VALUE  1568
#define IDC_STATIC_TOTAL_ASSETS         1569
#define IDC_STATIC_TOTAL_ASSETS_VALUE   1570
#define IDC_STATIC_PROFIT_LOSS_RATE     1571
#define IDC_STATIC_PROFIT_LOSS_RATE_VALUE 1572
#define IDC_STATIC_HAZARD_RATE          1573
#define IDC_STATIC_HAZARD_RATE_VALUE    1574
#define IDC_STATIC_AVAILABLE_DEPOSIT    1575
#define IDC_STATIC_AVAILABLE_DEPOSIT_VALUE 1576
#define IDC_STATIC_FREEZE_DEPOSIT       1577
#define IDC_STATIC_FREEZE_DEPOSIT_VALUE 1578
#define IDC_STATIC_YESTERDAY_EARNING_RATE 1579
#define IDC_STATIC_YESTERDAY_EARNING_RATE_VALUE 1580
#define IDC_STATIC_IMAGE                1581
#define IDC_STATIC_TOTAL_PROFIT_LOSS    1581
#define IDC_BUTTON_APPLY                1582
#define IDC_STATIC_TOTAL_PROFIT_LOSS_VALUE 1582
#define IDC_STATIC_SERVERTYPE           1583
#define IDC_STATIC_CONTINUE_PRFIT_DAYS  1583
#define IDC_BTN_REGISTER                1584
#define IDC_STATIC_CONTINUE_PRFIT_DAYS_VALUE 1584
#define IDC_STATIC_THIS_WEEK_EARNING_RATE 1585
#define IDC_STATIC_THIS_WEEK_EARNING_RATE_VALUE 1586
#define IDC_STATIC_OCCUPY_DEPOSIT       1587
#define IDC_STATIC_OCCUPY_DEPOSIT_VALUE 1588
#define IDC_STATIC_PROFIT_BEYOND_TEN_DAYS 1589
#define IDC_BTN_MAIN                    1590
#define IDC_STATIC_PROFIT_BEYOND_TEN_DAYS_VALUE 1590
#define IDC_BTN_QUOTE                   1591
#define IDC_STATIC_OCCUPY               1591
#define IDC_BTN_ANALYSIS                1592
#define IDC_STATIC_CURRENT_INTERSET     1592
#define IDC_BTN_FUNCTION                1593
#define IDC_STATIC_FLOAT_GAIN_LOST      1593
#define IDC_BTN_SYSSET                  1594
#define IDC_STATIC_OCCUPY_VALUE         1594
#define IDC_STATIC_CURRENT_INTERSET_VALUE 1595
#define IDC_STATIC_FLOAT_GAIN_LOST_VALUE 1596
#define IDC_EDIT_OLD_PW                 1597
#define IDC_EDIT_AFTER_PW               1598
#define ID_CLOSE_BTN                    1599
#define IDC_EDIT_CONFIRM_PW             1600
#define ID_MAX_BTN                      1601
#define ID_MIN_BTN                      1602
#define IDC_STATIC_PW_TYPE              1603
#define IDC_STATIC_OLD_PW               1604
#define ID_TOOLBAR_BTN                  1605
#define IDC_STATIC_NEW_PW               1606
#define IDC_STATIC_CONFIRM_PW           1607
#define IDC_COMBO_PW_TYPE               1608
#define IDC_BUTTON_OK                   1609
#define IDC_STATIC_SAVE_USER            1610
#define IDC_STATIC_PRO_USER             1611
#define IDC_BUTTON_SEARCH               1612
#define IDC_STATIC_PROCESS              1613
#define IDC_BTN_OPEN                    1614
#define ID_GUIDE_LAST                   1615
#define IDC_EDIT_RISE_MAXPROFIT         1616
#define IDC_EDIT_RISE_TOTALPROFIT       1617
#define ID_GUIDE_NEXT                   1618
#define IDC_EDIT_RISE_AVGPROFIT         1619
#define IDC_EDIT_MAX_SINGLE_LOSS        1620
#define IDC_EDIT_CUMULATIVE_LOSS        1621
#define IDC_EDIT_FALL_PROMPTCNT         1622
#define IDC_EDIT_SHAKE_PROMPTCNT        1623
#define IDC_EDIT_SHAKE_TOTALPROFIT      1624
#define IDC_EDIT_SHAKE_AVGPROFIT        1625
#define IDC_BUTTON_RISE_PERIOD          1626
#define IDC_BUTTON_FALL_PERIOD          1627
#define IDC_BUTTON_SHAKE_PERIOD         1628
#define IDC_STATIC_RELATIVEPROFIT       1629
#define IDC_STATIC_RELATIVE_PROFIT      1630
#define IDC_EDIT_RELATIVE_PROFIT        1631
#define IDC_SLIDER1                     1632
#define IDC_BTN_CLOSE                   1633
#define ID_BTN_CLOSE                    1634
#define IDC_CHECK_ONE_MINUTE            1635
#define IDC_CHECK_THREE_MINUTE          1636
#define IDC_CHECK_FIVE_MINUTE           1637
#define IDC_CHECK_TEN_MINUTE            1638
#define IDC_CHECK_FIFTEEN_MINUTE        1639
#define IDC_CHECK_THIRTY_MINUTE         1640
#define IDC_CHECK_SIXTY_MINUTE          1641
#define IDC_CHECK_120_MINUTE            1642
#define IDC_CHECK_180_MINUTE            1643
#define IDC_CHECK_240_MINUTE            1644
#define IDC_CHECK_DAY_LINE              1645
#define IDC_CHECK_WEEK_LINE             1646
#define IDC_CHECK_MONTH_LINE            1647
#define IDC_CHECK_YEAR_LINE             1648
#define IDC_STATIC_OTHER_NAME           1649
#define IDC_STATIC_PHONE                1650
#define IDC_STATIC_MAIL                 1651
#define IDC_STATIC_QQ                   1652
#define IDC_EDIT_OTHER_NAME             1653
#define IDC_EDIT_PHONE                  1654
#define IDC_EDIT_MAIL                   1655
#define IDC_BTN_PREV                    1655
#define IDC_BUTTON_EXCEL_IMP            1655
#define IDC_EDIT_QQ                     1656
#define IDC_BTN_NEXT                    1656
#define IDC_STATIC_GREEN_CHANNEL        1656
#define IDC_STATIC_USER_ACCOUNT         1657
#define IDC_STATIC_TRADENAME            1657
#define IDC_CHECK_GREEN_CHANNEL         1657
#define IDC_STATIC_CYCLE_TYPE           1658
#define IDC_STATIC_APPTYPE              1658
#define IDC_BUTTON_                     1658
#define IDC_STATIC_CYCLE_POSTFIX        1659
#define IDC_PROGRESS_DOWNLOAD           1659
#define IDC_EDIT_CYCLE_SET              1660
#define IDC_STATIC_TIME                 1661
#define IDC_STATIC_CION                 1662
#define IDC_STATIC_MARKET_IMPACKT       1663
#define IDC_STATIC_MARKET_IMPACT        1664
#define IDC_STATIC_FORMER_VALUE         1665
#define IDC_STATIC_FORECAST_VALUE       1666
#define IDC_STATIC_ACTUAL_VALUE         1667
#define IDC_STATIC_IMPORTANT_LEVEL      1668
#define IDC_STATIC_CONTENT              1669
#define IDC_STATIC_                     1670
#define IDC_STATIC_FORMER               1671
#define IDC_STATIC_FORECAST             1672
#define IDC_STATIC_ACTUAL               1673
#define IDC_EDIT_CONTENT                1674
#define IDC_BTN_MYTRADE                 1675
#define IDC_STATIC_IMP_TIPS             1680
#define IDC_PROGRESS2                   1681
#define IDC_PROGRESS3                   1682
#define IDC_BUTTON_IMP                  1683
#define ID_SUBMENU_BTN                  6000
#define ID_SUBMENU_BTN_END              6008
#define IDC_BUTTON_USER_IMPORT          10351
#define ID_BUTTON32771                  32771
#define ID_BUTTON32772                  32772
#define ID_WINDOW_SPLIT_ADD_RIGHT       32773
#define ID_WINDOW_SPLIT_ADD_LEFT        32774
#define ID_WINDOW_SPLIT_ADD_TOP         32775
#define ID_WINDOW_SPLIT_ADD_BOTTOM      32776
#define ID_WINDOW_SPLIT_ADD_TAB         32777
#define ID_WINDOW_SPLIT_DEL             32778
#define ID_LAYOUT_ADJUST                32779
#define ID_SETTING                      32780
#define IDM_CHART_BEGIN                 32781
#define IDM_CHART_PROP                  32781
#define IDM_CHART_INSERT                32782
#define IDM_CHART_DELETE                32783
#define IDM_CHART_DELETE_CURVE          32784
#define IDM_CHART_CANCEL                32785
#define IDM_CHART_INDEX                 32786
#define IDM_CHART_EXPORT                32787
#define IDM_CHART_CNP                   32788
#define IDM_CHART_CYCLE_BEGIN           32790
#define IDM_CHART_KMINUTE               32790
#define IDM_CHART_KDAY                  32791
#define IDM_CHART_KMINUTE5              32792
#define IDM_CHART_KMINUTE15             32793
#define IDM_CHART_KMINUTE30             32794
#define IDM_CHART_KMINUTE60             32795
#define IDM_CHART_KMINUTEX              32796
#define IDM_CHART_KDAYX                 32797
#define IDM_CHART_KWEEK                 32798
#define IDM_CHART_KMONTH                32799
#define IDM_CHART_KQUARTER              32800
#define IDM_CHART_KYEAR                 32801
#define IDM_CHART_KMINUTE180            32802
#define IDM_CHART_KMINUTE240            32803
#define IDM_CHART_KMINUTEMORE           32804
#define IDM_CHART_CYCLE_END             32805
#define IDM_CHART_KZUOBIAO              32806
#define IDM_CHART_KSTYLE1               32807
#define IDM_CHART_KSTYLE2               32808
#define IDM_CHART_KSTYLE3               32809
#define IDM_CHART_KSTYLE4               32810
#define IDM_CHART_KSTYLE5               32811
#define IDM_CHART_KSTYLE6               32812
#define IDM_CHART_INDEX_HELP            32813
#define IDM_CHART_INDEX_PARAM           32814
#define IDM_CHART_HIDE_INDEX            32815
#define IDM_CHART_TRADE_NEWTRADE        32816
#define IDM_CHART_TRADE_STOPLOSEBUY     32817
#define IDM_CHART_TRADE_LIMITPRICE      32818
#define IDM_CHART_ADDCMP_INDEX          32819
#define IDC_CHART_ADD2BLOCK_BEGIN       32870
#define IDC_CHART_ADD2BLOCK_END         32880
#define IDM_CHART_END                   32880
#define ID_GRIDHEAD_SET                 32881
#define IDM_STATUS_BEGIN                32882
#define IDM_STATUS_SHOW2                32882
#define IDM_STATUS_SHOW3                32883
#define IDM_STATUS_SHOW4                32884
#define IDM_STATUS_STOCK_SH             32885
#define IDM_STATUS_SZ                   32886
#define IDM_STATUS_FUTURESCN            32887
#define IDM_STATUS_HK                   32888
#define IDM_STATUS_GOLD                 32889
#define IDM_STATUS_FUTURES_SH           32890
#define IDM_STATUS_ZZ                   32891
#define IDM_STATUS_DL                   32892
#define IDM_STATUS_FIX                  32893
#define IDM_STATUS_OTHER                32894
#define IDM_STATUS_END                  32900
#define ID_BLOCK_SET                    32901
#define ID_OPEN_WORKSPACE               32902
#define ID_NEW_WORKSPACE                32903
#define ID_SAVEAS_WORKSPACE             32904
#define ID_NEW_CHILDFRAME               32905
#define ID_OPEN_CHILDFRAME              32906
#define ID_SAVEAS_CHILDFRAME            32907
#define ID_CLOSE_CHILDFRAME             32908
#define ID_CLOSE_WORKSPACE              32909
#define IDM_BLOCK_BEGIN                 32910
#define IDM_BLOCK_CHANGE                32910
#define IDM_BLOCK_INSERT                32911
#define IDM_BLOCK_SET                   32912
#define IDM_BLOCK_DELETE                32913
#define IDM_BLOCK_CANCEL                32914
#define IDM_BLOCK_END                   32920
#define ID_FORMULA_MAG                  32921
#define IDM_STD_BEGIN                   33302
#define IDM_STD_END                     33349
#define ID_PIC_BEGIN                    33350
#define ID_PIC_TREND                    33350
#define ID_PIC_KLINE                    33351
#define ID_PIC_TICK                     33352
#define ID_PIC_PRICE                    33353
#define ID_PIC_TIMESALE                 33354
#define ID_PIC_NEWS                     33355
#define ID_PIC_DETAIL                   33356
#define ID_PIC_REPORT                   33357
#define ID_PIC_HIDE_INMENU              33358
#define ID_PIC_STARRY                   33358
#define ID_PIC_CAPITALFLOW              33359
#define ID_PIC_BLOCKREPORT              33360
#define ID_PIC_MAIN_TIMESALE            33361
#define ID_PIC_REPORT_RANK              33362
#define ID_PIC_REPORT_SELECT            33363
#define ID_PIC_DADANPAIHANG             33364
#define ID_PIC_VALUE                    33365
#define ID_PIC_EXPTREND                 33366
#define ID_PIC_FENJIABIAO               33367
#define ID_PIC_CHOUMA                   33368
#define ID_PIC_PHASESORT                33369
#define ID_PIC_DUOGUTONGLIE             33370
#define ID_PIC_KLINEARBITRAGE           33371
#define ID_PIC_REPORT_ARBITRAGE         33372
#define ID_PIC_TRENDARBITRAGE           33373
#define ID_PIC_WEB_NEWS                 33374
#define ID_PIC_QR_CODE                  33375
#define ID_PIC_MULTI_RANK               33376
#define ID_PIC_DUANXIANJIANKONG         33377
#define ID_PIC_MULTI_CYCLE_KLINE        33378
#define ID_PIC_POSITIONS                33379
#define ID_PIC_TREND_ANALYSIS           33380
#define ID_PIC_DK_MONEY                 33381
#define ID_PIC_MAIN_COST                33382
#define ID_PIC_SUGGEST_POSITION         33383
#define ID_PIC_WEB_CAPITAL_FLOW         33384
#define ID_PIC_ADD_USER_BLOCK           33385
#define ID_PIC_TIMESALE_RANK            33386
#define ID_PIC_TIMESALE_STATISTIC       33387
#define ID_PIC_SMART_CHOOSE_STOCK       33388
#define ID_PIC_REPORT_NEWSTOCK			33389
#define ID_PIC_END                      33468
#define ID_UPDATE                       33469
#define ID_EXPORT                       33470
#define ID_MENUITEM33061                33471
#define ID_INFO_SH_BOURSE               33471
#define ID_MENUITEM33062                33472
#define ID_INFO_SZ_BOURSE               33472
#define ID_MENUITEM33063                33473
#define ID_INFO_HK_BOURSE               33473
#define ID_MENUITEM33064                33474
#define ID_INFO_F10                     33474
#define ID_INFO_NEWS                    33476
#define ID_SAVE_WORKSPACE               33477
#define IDM_USER1                       33491
#define IDM_USER2                       33492
#define IDM_USER3                       33493
#define IDM_USER4                       33494
#define ID_VIEW_SDBAR                   33495
#define IDT_SD_BEGIN                    33497
#define IDT_SD_LINE                     33497
#define IDT_SD_LINEEX                   33498
#define IDT_SD_JGTD                     33499
#define IDT_SD_PXZX                     33500
#define IDT_SD_YHX                      33501
#define IDT_SD_HJFG                     33502
#define IDT_SD_BFB                      33503
#define IDT_SD_BD                       33504
#define IDT_SD_JX                       33505
#define IDT_SD_JXHGD                    33506
#define IDT_SD_YCXXHGD                  33507
#define IDT_SD_XXHGD                    33508
#define IDT_SD_ZQ                       33509
#define IDT_SD_FBLQ                     33510
#define IDT_SD_ZS                       33511
#define IDT_SD_JEJD                     33512
#define IDT_SD_45UP                     33513
#define IDT_SD_45DOWN                   33514
#define IDT_SD_VERTICAL                 33515
#define IDT_SD_HORIZONTAL               33516
#define IDT_SD_ZBJ                      33517
#define IDT_SD_DBJ                      33518
#define IDT_SD_TEXT                     33519
#define IDT_SD_COLOR                    33520
#define IDT_SD_DELETE                   33521
#define IDT_SD_END                      33522
#define ID_BROKER_WATCH                 33523
#define ID_VIEW_CALC                    33524
#define ID_CPS_SXBD                     33525
#define IDM_IOVIEWREPORT_BEGIN          33526
#define IDM_IOVIEWREPORT_GRIDLINE       33527
#define IDM_IOVIEWREPORT_DELOWNSEL      33528
#define IDM_IOVIEWREPORT_OWNSEL_UP      33529
#define IDM_IOVIEWREPORT_OWNSEL_DOWN    33530
#define IDM_IOVIEWREPORT_OWN_DOWNLOAD   33531
#define IDM_IOVIEWREPORT_OWN_UPLOAD     33532
#define IDM_IOVIEWREPORT_END            33532
#define ID_SELECT_STOCK                 33533
#define ID_DEL_VIEW                     33566
#define ID_ADD_UPVIEW                   33567
#define ID_ADD_DOWNVIEW                 33568
#define ID_ADD_LEFTVIEW                 33569
#define ID_ADD_RIGHTVIEW                33570
#define ID_DISCONNECT                   33571
#define ID_CONNECT                      33572
#define IDM_IOVIEW_DETAIL_TREND         33573
#define IDM_IOVIEW_DETAIL_SANE          33574
#define IDM_IOVIEW_STARRY_START         33600
#define IDM_IOVIEW_STARRY_CANCELZOOM    33601
#define IDM_IOVIEW_STARRY_BLINKUSER     33602
#define IDM_IOVIEW_STARRY_EXPORTBLOCK   33603
#define IDM_IOVIEW_STARRY_COR_NORMAL    33604
#define IDM_IOVIEW_STARRY_COR_LOGARITHM 33605
#define IDM_IOVIEW_STARRY_STARRY_ADD    33606
#define IDM_IOVIEW_STARRY_STARRY_SUB    33607
#define IDM_IOVIEW_STARRY_END           33650
#define IDM_IOVIEWBASE_BEGIN            34000
#define IDM_IOVIEWBASE_ADD_OWNSEL       34001
#define IDM_IOVIEWBASE_ADD_IOVIEW       34002
#define IDM_IOVIEWBASE_TAB              34003
#define IDM_IOVIEWBASE_MERCH_CHANGE     34004
#define IDM_IOVIEWBASE_F7               34005
#define IDM_IOVIEWBASE_FONT_BIGGER      34006
#define IDM_IOVIEWBASE_FONT_SMALLER     34007
#define IDM_IOVIEWBASE_SPLIT_TOP        34008
#define IDM_IOVIEWBASE_SPLIT_BOTTOM     34009
#define IDM_IOVIEWBASE_SPLIT_LEFT       34010
#define IDM_IOVIEWBASE_SPLIT_RIGHT      34011
#define IDM_IOVIEWBASE_CLOSE            34012
#define IDM_IOVIEWBASE_CLOSECUR         34013
#define IDM_IOVIEWBASE_RETURN           34014
#define IDM_IOVIEWBASE_END              34015
#define IDM_IOVIEWKLINE_ALLINDEX_BEGIN  34020
#define IDM_IOVIEWKLINE_ALLINDEX_END    34220
#define IDM_IOVIEWKLINE_OFTENINDEX_BEGIN 34221
#define IDM_IOVIEWKLINE_OFTENINDEX_END  34421
#define IDM_IOVIEWKLINE_OWNINDEX_BEGIN  34422
#define IDM_KLINE_TREND_INDEX           34423
#define IDM_KLINE_SANE_INDEX            34424
#define IDM_IOVIEWKLINE_OWNINDEX_END    34425
#define IDM_IOVIEWKLINE_EXPERT_BEGIN    34426
#define IDM_IOVIEWKLINE_EXPERT_END      34500
#define IDM_WINDOW_CLOSE                34501
#define ID_DISCONNECT_SERVER            34503
#define ID_CONNECT_SERVER               34504
#define ID_TOOL_ICON_BEGIN              34600
#define ID_TOOL_ICON_TREND              34601
#define ID_TOOL_ICON_TREND2             34602
#define ID_TOOL_ICON_TICK               34603
#define ID_TOOL_ICON_TICK2              34604
#define ID_TOOL_ICON_KLINE              34605
#define ID_TOOL_ICON_KLINE2             34606
#define ID_TOOL_ICON_PRICE              34607
#define ID_TOOL_ICON_PRICE2             34608
#define ID_TOOL_ICON_TIMESALE           34609
#define ID_TOOL_ICON_TIMESALE2          34610
#define ID_TOOL_ICON_NEWS               34611
#define ID_TOOL_ICON_NEWS2              34612
#define ID_TOOL_ICON_F10                34613
#define ID_TOOL_ICON_F102               34614
#define ID_TOOL_ICON_DETAIL             34615
#define ID_TOOL_ICON_DETAIL2            34616
#define ID_TOOL_ICON_REPORT             34617
#define ID_TOOL_ICON_REPORT2            34618
#define ID_TOOL_ICON_KLINE_CYCLE        34619
#define ID_TOOL_ICON_KLINE_CYCLE2       34620
#define ID_TOOL_ICON_CHOOSE_INDEX       34621
#define ID_TOOL_ICON_CHOOSE_INDEX2      34622
#define ID_TOOL_ICON_FORMULAR           34623
#define ID_TOOL_ICON_FORMULAR2          34624
#define ID_TOOL_ICON_GRIDHEAD_SET       34625
#define ID_TOOL_ICON_GRIDHEAD_SET2      34626
#define ID_TOOL_ICON_BLOCK_SET          34627
#define ID_TOOL_ICON_BLOCK_SET2         34628
#define ID_TOOL_ICON_SYSTEMFACE_SET     34629
#define ID_TOOL_ICON_SYSTEMFACE_SET2    34630
#define ID_TOOL_ICON_LAYOUT_SET         34631
#define ID_TOOL_ICON_LAUOUT_SET2        34632
#define ID_TOOL_ICON_OWNDRAW_LINE       34633
#define ID_TOOL_ICON_OWNDRAW_LINE2      34634
#define ID_TOOL_ICON_SYSTEM_UPDATE      34635
#define ID_TOOL_ICON_SYSTEM_UPDATE2     34636
#define ID_TOOL_ICON_ONLINE_HELP        34637
#define ID_TOOL_ICON_ONLINE_HELP2       34638
#define ID_TOOL_ICON_NEW_CHILDFRAME     34639
#define ID_TOOL_ICON_NEW_CHILDFRAME2    34640
#define ID_TOOL_ICON_NEW_WORKSPACE      34641
#define ID_TOOL_ICON_NEW_WORKSPACE2     34642
#define ID_TOOL_ICON_SAVE_WORKSPACE     34643
#define ID_TOOL_ICON_SAVE_WORKSPACE2    34644
#define ID_TOOL_ICON_RETURN             34645
#define ID_TOOL_ICON_RETURN2            34646
#define ID_TOOL_ICON_FONT_BIG           34647
#define ID_TOOL_ICON_FONT_BIG2          34648
#define ID_TOOL_ICON_FONT_SMALL         34649
#define ID_TOOL_ICON_FONT_SMALL2        34650
#define ID_TOOL_ICON_PAGE_UP            34651
#define ID_TOOL_ICON_PAGE_UP2           34652
#define ID_TOOL_ICON_PAGE_DOWN          34653
#define ID_TOOL_ICON_PAGE_DOWN2         34654
#define ID_TOOL_ICON_CHART_XZOOMIN      34655
#define ID_TOOL_ICON_CHART_XZOOMIN2     34656
#define ID_TOOL_ICON_CHART_XZOOMOUT     34657
#define ID_TOOL_ICON_CHART_XZOOMOUT2    34658
#define ID_TOOL_ICON_CHART_YZOOMIN      34659
#define ID_TOOL_ICON_CHART_YZOOMIN2     34660
#define ID_TOOL_ICON_CHART_YZOOMOUT     34661
#define ID_TOOL_ICON_CHART_YZOOMOUT2    34662
#define ID_TOOL_ICON_F7MAX              34663
#define ID_TOOL_ICON_F7MAX2             34664
#define ID_TOOL_ICON_F7RETURN           34665
#define ID_TOOL_ICON_F7RETURN2          34666
#define ID_TOOL_ICON_DEL_VIEW           34667
#define ID_TOOL_ICON_DEL_VIEW2          34668
#define ID_TOOL_ICON_69                 34669
#define ID_TOOL_ICON_70                 34670
#define ID_TOOL_ICON_71                 34671
#define ID_TOOL_ICON_72                 34672
#define ID_TOOL_ICON_73                 34673
#define ID_TOOL_ICON_74                 34674
#define ID_TOOL_ICON_75                 34675
#define ID_TOOL_ICON_NOUSE              34800
#define ID_TOOL_ICON_END                34800
#define IDM_PRE_WEIGHT                  34807
#define IDM_AFT_WEIGHT                  34808
#define IDM_NONE_WEIGHT                 34809
#define ID_INDEX_CHOOSE_STOCK           34811
#define ID_RESPONSIBILITY               34812
#define ID_MENU_F10_BEGIN               34900
#define ID_MENU_F10_END                 35000
#define ID_MENU_IOVIEWREPORT_MORE_BEGIN 35001
#define ID_MENU_IOVIEWREPORT_MORE_BGN1  35001
#define ID_MENU_IOVIEWREPORT_MORE_END1  35050
#define ID_MENU_IOVIEWREPORT_MORE_BGN2  35051
#define ID_MENU_IOVIEWREPORT_MORE_END2  35100
#define ID_MENU_IOVIEWREPORT_MORE_END   35100
#define ID_DLGSYNCEXCEL                 35101
#define IDM_COLOR_KLINE_PROMPT          35103
#define IDM_TRADE_PROMPT                35104
#define IDM_REMOVE_ALL_PROMPT           35105
#define ID_VIEW_TB_SPECIAL              35106
#define ID_SPECIAL_START                35107
#define ID_SPECIAL_INDEX_START          35107
#define ID_SPECIAL_RISEFALL             35108
#define ID_SPECIAL_MAJORCOST            35109
#define ID_SPECIAL_HOLDRISK             35110
#define ID_SPECIAL_STOCKTRADE           35111
#define ID_SPECIAL_STOCKLOW             35112
#define ID_SPECIAL_STOCKHIGH            35113
#define ID_SPECIAL_STOCKCOW             35114
#define ID_SPECIAL_GGMAJORCOST          35115
#define ID_SPECIAL_GGHOLDRISK           35116
#define ID_SPECIAL_JINDTD               35117
#define ID_SPECIAL_JINDGL               35118
#define ID_SPECIAL_QUSX                 35119
#define ID_SPECIAL_QUSZX                35120
#define ID_SPECIAL_QUSCP                35121
#define ID_SPECIAL_INDEX_END            35124
#define ID_SPECIAL_SELECT_START         35125
#define ID_SPECIAL_JGLT                 35125
#define ID_SPECIAL_XPJS                 35126
#define ID_SPECIAL_ZJZT                 35127
#define ID_SPECIAL_NSQL                 35128
#define ID_SPECIAL_CDFT                 35129
#define ID_SPECIAL_ZLXG                 35130
#define ID_SPECIAL_SLXS                 35131
#define ID_SPECIAL_HFFL                 35132
#define ID_SPECIAL_SHJD                 35133
#define ID_SPECIAL_XZDF                 35134
#define ID_SPECIAL_QZHQ                 35135
#define ID_SPECIAL_DXQS                 35136
#define ID_SPECIAL_SLQF                 35137
#define ID_SPECIAL_END                  35140
#define IDM_BELONG_BLOCK                35141
#define IDR_NET_FLOW                    35142
#define ID_DISCONNECT_NEWSSERVER        35143
#define ID_CONNECT_NEWSSERVER           35144
#define ID_CONNECT_SETTING              35145
#define ID_BLOCK_ADDTOFIRST             35146
#define ID_BLOCK_DELETEFROMFIRST        35147
#define ID_BLOCK_REMOVEFROM             35148
#define ID_BLOCK_ADDTO                  35149
#define ID_CHOOSESIMPLESTOCK            35150
#define ID_TREND_SINGLESECTION          35151
#define ID_TREND_MULTIDAY1              35152
#define ID_TREND_MULTIDAY2              35153
#define ID_TREND_MULTIDAY3              35154
#define ID_TREND_MULTIDAY4              35155
#define ID_TREND_MULTIDAY5              35156
#define ID_TREND_MULTIDAY6              35157
#define ID_TREND_MULTIDAY7              35158
#define ID_TREND_MULTIDAY8              35159
#define ID_TREND_MULTIDAY9              35160
#define ID_TREND_MULTIDAY10             35161
#define ID_REPORT_AUTOPAGE              35163
#define ID_REPORT_AUTOPAGESETTING       35164
#define ID_SAVE_CUR_CHILDFRAME          35165
#define ID_LOCK_CUR_CHILDFRAME          35166
#define ID_CLOSE_ALL_WINDOW             35167
#define ID_TOOLBAR_RIGHT                35168
#define ID_IOVIEWREPORT_NEW_BEGIN       36000
#define ID_IOVIEWREPORT_NEW_END         46000
#define ID_VIEW_LOCKMINMAX              46001
#define ID_DOWNLOAD                     46002
#define ID_KLINE_ADDCMPMERCH            46003
#define ID_KLINE_AUTOADDEXPCMPMERCH     46004
#define ID_KLINE_REMOVECMPMERCH         46005
#define ID_TREND_SHOWRFMAX              46006
#define ID_TREND_RFMAXAXIS              46007
#define ID_TREND_SHOWPERCENT            46008
#define ID_MERCH_NOTEPAD                46009
#define ID_CUSTOM_STOCK                 46010
#define ID_VEDIO_TRAINNING              46011
#define ID_MARK_CANCEL                  46012
#define ID_MARK_TEXT                    46013
#define ID_MARK_1                       46014
#define ID_MARK_2                       46015
#define ID_MARK_3                       46016
#define ID_MARK_4                       46017
#define ID_MARK_5                       46018
#define ID_MARK_6                       46019
#define ID_MARK_MANAGER                 46020
#define ID_MARKETRADAR                  46021
#define ID_MARKETRADAR_ADDRESULT        46022
#define ID_MAIN_MENU_START              46023
#define ID_AUTOPAGE_SETTING             46023
#define ID_FUNC_CONDITIONALARM          46024
#define ID_FUNC_MAINMONITOR             46025
#define ID_FUNC_ADDTOBLOCK              46026
#define ID_FUNC_DELFROMBLOCK            46027
#define ID_AUTOPAGE                     46028
#define ID_ZongHePaiMing                46029
#define ID_ReMenBanKuai                 46031
#define ID_DaPanZouShi                  46032
#define ID_InfoMine                     46033
#define ID_FUNC_REAL_TRADING            46034
#define ID_SYS_AUTO_RUN                 46035
#define ID_MAIN_MENU_END                46050
#define ID_CHART_INTERVALSTATISTIC      46051
#define ID_CHART_QUANTSTATISTIC         46052
#define ID_KLINE_HISTORYTREND           46053
#define ID_CHART_CHANGETAB              46054
#define ID_KLINE_AXISYNORMAL            46055
#define ID_KLINE_AXISYPERCENT           46056
#define ID_KLINE_AXISYLOG               46057
#define ID_TREND_SHOWTICK               46058
#define ID_TICK_SHOWTREND               46059
#define ID_TICK_DAY1                    46060
#define ID_TICK_DAY2                    46061
#define ID_TICK_DAY3                    46062
#define ID_TICK_DAY4                    46063
#define ID_TICK_DAY5                    46064
#define ID_TICK_DAY6                    46065
#define ID_TICK_DAY7                    46066
#define ID_TICK_DAY8                    46067
#define ID_TICK_DAY9                    46068
#define ID_TICK_DAY10                   46069
#define ID_TICK_CANCELZOOM              46070
#define ID_PIC_CFM_MULTIINTERVAL        46071
#define ID_PIC_CFM_MULTIMERCH           46072
#define ID_IWANTBUY                     46073
#define ID_ZHONGCANGCHIGU               46074
#define IDM_SETUPALARM                  46075
#define ID_TREND_SHOWVOLCOLOR           46076
#define ID_TRADEEXE_SETTING             46077
#define ID_MENUITEM46077                46078
#define ID_ARBITRAGE                    46079
#define ID_REPORT_TYPEBEGIN             46080
#define ID_REPORT_TYPEEND               46100
#define IDM_BLOCKMENU_BEGIN4            46101
#define IDM_BLOCKMENU_END4              46786
#define ID_ARBITRAGE_SETTING            46787
#define ID_ARBKLINE_CLOSEDIFF           46789
#define ID_ARBKLINE_AVGDIFF             46790
#define ID_ARBKLINE_KLINE               46791
#define ID_ARBKLINE_TWOLEG              46792
#define ID_ARBKLINE_END                 46795
#define IDM_ARBITRAGE_BEGIN             46796
#define IDM_ADD_ARBITRAGE               46796
#define IDM_MODIFY_ARBITRAGE            46797
#define IDM_DEL_ARBITRAGE               46798
#define IDM_ARBREPORT_GRIDLINE          46800
#define IDM_ARBITRAGE_END               46800
#define IDM_ARBTTRAGE_SELECT            46801
#define ID_TREND_SHOWAVG_PRICE          46802
#define IDM_ARBITRAGE_SHOWNEXTCHART     46803
#define ID_HOLD_NEW                     46804
#define ID_HOLD_CLOSE                   46805
#define ID_HOLD_TRACK                   46806
#define ID_HOLD_GAINVIEWSTYLE           46807
#define ID_HOLD_SHOWHIRE                46808
#define ID_HOLD_SHOWTAX                 46809
#define ID_HOLD_SHOWNOTE                46810
#define ID_HOLD_AUTOCOLUMN              46811
#define ID_HOLD_SHOWGRID                46812
#define ID_HOLD_MODIFY                  46813
#define ID_HOLD_LONGTIME                46814
#define ID_HISTORY_QUERYALL             46815
#define ID_HISTORY_QUERY3M              46816
#define ID_HISTORY_QUERY1M              46817
#define ID_HISTORY_QUERYTODAY           46818
#define ID_HISTORY_QUERYUSER            46819
#define ID_HISTORY_SAVESIMPLE           46820
#define ID_HISTORY_SAVE                 46821
#define ID_HOLD_RELATECHANGE            46829
#define ID_REPORT_FOREX_BEGIN           46830
#define ID_REPORT_FOREX_NEWTRADE        46830
#define ID_REPORT_FOREX_NEWORDER        46831
#define ID_REPORT_FOREX_NEWCOCO         46832
#define ID_REPORT_FOREX_END             46835
#define ID_HOLD_CLOSEALL                46836
#define ID_BUTTON46838                  46838
#define ID_BUTTON46839                  46839
#define ID_BUTTON46840                  46840
#define ID_RESTORE_VIEWSP               46845
#define ID_VIEW_COMMENT_BAR             46853
#define ID_MENU_AUTOCONNECT             46856
#define ID_EXPORT_DATA                  46858
#define ID_FDSF                         46859
#define ID_Menu                         46865
#define ID_ANALYSIS_CJMX                46866
#define ID_ANALYSIS_TLKX                46867
#define ID_MENU_DEFAULT_VALUE           46869
#define ID_USE_HELP                     46881
#define ID_USER_SERVICE                 46882
#define ID_KLINE46882                   46882
#define ID_SPECIAL_INFO_JP              46886
#define ID_SPECIAL_INFO_GPZX            46887
#define ID_SPECIAL_INFO_CJRL            46888
#define ID_SPECIAL_INFO_GJS             46889
#define ID_SPECIAL_TRADE_INTERNAL       46890
#define ID_SPECIAL_TRADE_PLUGIN         46891
#define ID_SPECIAL_LIVE_VIDEO           46892
#define ID_SPECIAL_LIVE_TEXT            46893
#define ID_SPECIAL_FUNC_ARBITRAGE       46894
#define ID_INVESTMENT_DIARY             46895
#define ID_BUTTON46866                  46896
#define IDM_BLOCKMENU_BEGIN             46900
#define ID_TEACHER_TEAM                 46901
#define ID_VIP_1V1                      46902
#define ID_LIVE_VIDEO                   46903
#define IDC_INTERVAL_SORT               46904
#define ID_NEWS_TRANSFER                46906
#define ID_DOMESTIC_FINANCE             46907
#define ID_INTERNATIONAL_FINANCE        46908
#define ID_INDUSTRY_NEWS                46909
#define ID_MARKET_REVIEW                46910
#define ID_RESEARCH_REPORT              46911
#define ID_DELEGATE_TRADE               46912
#define ID_TRADE_SETTING                46913
#define ID_CLASS_ROOM                   46914
#define ID_BUTTON46917                  46917
#define ID_SHOW_                        46919
#define ID_SHOW_SHORTCUT_BAR            46920
#define ID_SHORTCUT_MENU                46922
#define ID_BUTTON46923                  46923
#define ID_BUTTON46925                  46925
#define ID_BUTTON46926                  46926
#define ID_SCTOOLBAR_MENU               46929
#define ID_Quotation_HS                 46939
#define ID_Quotation_INDEX              46940
#define ID_Quotation_HK                 46941
#define ID_Quotation_FUT                46942
#define IDM_BLOCKMENU_END               47900
#define ID_MENU_USER_NAME               49000
#define ID_MENU_LOGIN                   49010
#define ID_MENU_REGISTER                49020
#define ID_MENU_SYSTEM                  49030
#define ID_MENU_FORMULA_MANAGE          49040
#define ID_MENU_ALARM                   49050
#define ID_MENU_SEL_STOCK               49060
#define ID_MENU_TRADE                   49070
#define ID_MENU_HELP                    49080
#define ID_MENU_EXIT                    49090
#define ID_MODULE_SETTING               49091
#define ID_MENU_SIMULATION_TRADE        49092
#define IDM_INDEXMENU_BEGIN             49900
#define IDM_INDEXMENU_END               50900
#define ID_IOVIEWREPORT_NEW_TOP_BEGIN   51000
#define ID_IOVIEWREPORT_NEW_TOP_END     61000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        743
#define _APS_NEXT_COMMAND_VALUE         46945
#define _APS_NEXT_CONTROL_VALUE         1659
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
