#ifndef _MAIN_MSG_DEF_H_
#define _MAIN_MSG_DEF_H_


#define WM_MAIN_MSGBEGIN WM_USER+0x100	


enum E_MainMsgDef
{
	UM_MY_ADD_MERCH  = WM_MAIN_MSGBEGIN,
	UM_MY_REMOVE_MERCH,
	TEST_VIEWDATA_INFOMINELIST_RESP,
	TEST_VIEWDATA_INFOMINECONTENT_RESP,
	
	UM_DOINITIALIZE,			// 因为原始数据不是排序的数据，所以采取在初始化时机申请100个数据，然后只插入更新的动态数据


	TEMP_UM_CHOUMANOTIFY,

	UM_BLOCK_DOINITIALIZE,
	UM_MYMSG_BASE ,
	UM_DOCALC,
	UM_CALCMSG,
	UM_CALCMSG_END,

	UM_DO_INITFROMXML,	// 负责初始化的消息

	UM_STARRY_INITIALIZE_ALLMERCHS,
	UM_STARRY_UPDATEXY,


	UM_DOTRACEMENU,

	UM_UserSelectListItem,

	UM_CHECK_CFM_HIDE,			// 检查页面是否被隐藏了，如果隐藏了，显示它~~

	UM_DO_ORGDATAUPDATE,

	UM_CHANGE_USERINFO_SUCC,	// 修改用户信息成功

	UM_WEB_COMMAND,				// web端命令
	UM_WEB_CALL_BACK,			// web调用PC的回调
};

#endif